(self.AMP=self.AMP||[]).push({n:"amp-viewer-integration",p:"high",v:"1525381599226",f:(function(AMP){function k(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var l=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;self.log=self.log||{user:null,dev:null,userForEmbed:null};var m=self.log;function p(){if(!m.user)throw Error("failed to call initLogConstructor");return m.user};function q(a){return a||{}};function r(a){this.H=a;this.h=Object.create(null)}r.prototype.get=function(a){if(this.h[a])return this.h[a].access=Date.now(),this.h[a].payload};r.prototype.put=function(a,b){var c=this;this.h[a]={payload:b,access:Date.now()};var d=Object.keys(this.h);if(d.length>this.H){if(m.dev)a=m.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming template cache");d.sort(function(a,b){return c.h[b].access-c.h[a].access});delete this.h[d[d.length-1]]}};var t=self.AMP_CONFIG||{},u=("string"==typeof t.cdnProxyRegex?new RegExp(t.cdnProxyRegex):t.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;var v=q({c:!0,v:!0,a:!0,ad:!0}),w,x,y=/[?&]amp_js[^&]*/,z=/[?&]usqp[^&]*/;
function A(a){var b;w||(w=self.document.createElement("a"),x=self.UrlCache||(self.UrlCache=new r(100)));var c=x.get(a);if(c)return c;var d=w;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var f=e,g=f;if(b)return g;x.put(a,g);return g}
function B(a){"string"==typeof a&&(a=A(a));var b=a;"string"==typeof b&&(b=A(b));if(!u.test(b.origin))return a.href;var b=a.pathname.split("/"),c=b[1];p().assert(v[c],"Unknown path prefix in url %s",a.href);var d=b[2],e="s"==d?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(d);p().assert(0<e.indexOf("."),"Expected a . in origin %s",e);b.splice(1,"s"==d?3:2);b=e+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(y,"").replace(z,"").replace(/^[?&]/,""))?"?"+c:"":"";return b+c+(a.hash||
"")};function C(a,b){var c,d=a=a.__AMP_TOP||a,e=a,f=D(d),g=f["viewer-integration-variable"];g||(g=f["viewer-integration-variable"]={obj:null,promise:null,resolve:null,context:null,ctor:null});g.ctor||g.obj||(g.ctor=b,g.context=e,g.resolve&&E(d,"viewer-integration-variable"));c&&E(a,"viewer-integration-variable")}function F(a){a=H(a);a=H(a);a=a.isSingleDoc()?a.win:a;return E(a,"viewer")}
function H(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=E(b,"ampdoc").getAmpDoc(a)}return a}function E(a,b){var c=D(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function D(a){var b=a.services;b||(b=a.services={});return b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function I(a){return a.parent&&a.parent!=a};var J;function K(a,b,c,d){function e(a){try{return g(a)}catch(G){throw self.reportError(G),G;}}var f=a,g=c,h=L(),n=!1;d&&(n=d.capture);f.addEventListener(b,e,h?d:n);return function(){f&&f.removeEventListener(b,e,h?d:n);e=f=g=null}}function L(){if(void 0!==J)return J;J=!1;try{var a={get capture(){J=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return J};function aa(a,b){return K(a,"message",b,void 0)}function ba(a,b){var c=b,d=K(a,"unload",function(a){try{c(a)}finally{c=null,d()}},void 0)};function M(a){var b=this;this.B=a;this.R={ancestorOrigin:function(){var a=b.B.win.location.ancestorOrigins;return a?a[0]:""},fragmentParam:function(a,d){var c=d;p().assert(a,"The first argument to FRAGMENT_PARAM, the fragment string param is required");p().assert("string"==typeof a,"param should be a string");var f=b.B.win.location.originalHash,g=Object.create(null);if(f)for(var h;h=l.exec(f);){var n=k(h[1],h[1]);h=h[2]?k(h[2],h[2]):"";g[n]=h}return void 0===g[a]?c:g[a]}}}M.prototype.get=function(){return this.R};var ca="altKey charCode ctrlKey detail eventPhase keyCode layerX layerY metaKey pageX pageY returnValue shiftKey timeStamp type which".split(" "),da="clientX clientY force identifier pageX pageY radiusX radiusY screenX screenY".split(" ");function N(a,b){this.win=a;this.M=b;this.o=!1;this.w=[];b.registerHandler("scrollLock",this.O.bind(this));O(this)}
function O(a){var b=a.I.bind(a),c=a.win.document,d={capture:!1,passive:!a.o};a.w.push(K(c,"touchstart",b,d),K(c,"touchend",b,d),K(c,"touchmove",b,d))}function ea(a){a.w.forEach(function(a){return a()});a.w.length=0}N.prototype.I=function(a){switch(a.type){case "touchstart":case "touchend":case "touchmove":if(a&&a.type){var b=P(a,ca);a.touches&&(b.touches=Q(a.touches));a.changedTouches&&(b.changedTouches=Q(a.changedTouches));this.M.sendRequest(a.type,b,!1)}this.o&&a.preventDefault()}};
function Q(a){for(var b=[],c=0;c<a.length;c++)b.push(P(a[c],da));return b}function P(a,b){for(var c={},d=0;d<b.length;d++){var e=b[d];void 0!==a[e]&&(c[e]=a[e])}return c}N.prototype.O=function(a,b,c){this.o=!!b;ea(this);O(this);return c?Promise.resolve({}):void 0};function R(a){if("string"!=typeof a)return a;if("{"!=a.charAt(0))return null;try{return JSON.parse(a)}catch(b){return null}}function S(a,b,c){this.win=a;this.F=b;this.G=c}S.prototype.addEventListener=function(a,b){var c=this;this.win.addEventListener("message",function(a){a.origin==c.F&&a.source==c.G&&"__AMPHTML__"==a.data.app&&b(a)})};S.prototype.postMessage=function(a){this.G.postMessage(a,this.F)};S.prototype.start=function(){};
function T(a,b,c){this.win=a;this.m=b;this.L=!!c;this.N=0;this.A={};this.l={};this.C=null;this.m.addEventListener("message",this.J.bind(this));this.m.start()}T.prototype.registerHandler=function(a,b){this.l[a]=b};T.prototype.unregisterHandler=function(a){delete this.l[a]};T.prototype.setDefaultHandler=function(a){this.C=a};
T.prototype.J=function(a){if(a=R(a.data))if("q"==a.type)fa(this,a);else if("s"==a.type){var b=a.requestid,c=this.A[b];c&&(delete this.A[b],a.error?(U(this,"amp-viewer-messaging: handleResponse_ error: ",a.error),c.reject(Error("Request "+a.name+" failed: "+a.error))):c.resolve(a.data))}};T.prototype.sendRequest=function(a,b,c){var d=this,e=++this.N,f=void 0;c&&(f=new Promise(function(a,b){d.A[e]={resolve:a,reject:b}}));V(this,{app:"__AMPHTML__",requestid:e,type:"q",name:a,data:b,rsvp:c});return f};
function W(a,b,c,d){var e=X(d);U(a,"amp-viewer-messaging: sendResponseError_, Message name: "+c,e);V(a,{app:"__AMPHTML__",requestid:b,type:"s",name:c,data:null,error:e})}function V(a,b){a.m.postMessage(a.L?JSON.stringify(b):b)}
function fa(a,b){var c=a.l[b.name];c||(c=a.C);if(!c)throw c=Error("Cannot handle request because handshake is not yet confirmed!"),c.args=b.name,c;c=c(b.name,b.data,!!b.rsvp);if(b.rsvp){var d=b.requestid;if(!c)throw W(a,d,b.name,Error("no response")),Error("expected response but none given: "+b.name);c.then(function(c){V(a,{app:"__AMPHTML__",requestid:d,type:"s",name:b.name,data:c})},function(c){W(a,d,b.name,c)})}}
function U(a,b,c){var d="amp-messaging-error-logger: "+b,e=" data: "+X(c),d=d+e;a.win.viewerState=d}function X(a){return a?a.message?a.message:String(a):"unknown error"};function Y(a){var b=this;this.win=a;this.D=this.j=!1;this.P=new M(H(this.win.document));C(this.win,function(){return b.P.get()})}
Y.prototype.init=function(){var a=this,b=F(this.win.document);this.j="1"==b.getParam("webview");this.D=b.hasCapability("handshakepoll");var c=b.getParam("origin")||"";if(!this.j&&!c)return Promise.resolve();var d=H(this.win.document);if(this.j||this.D){var e=I(this.win)?this.win.parent:null;return ga(this,e,c).then(function(e){return Z(a,b,d,c,new T(a.win,e,a.j))})}e=new S(this.win,c,this.win.parent);return Z(this,b,d,c,new T(this.win,e,this.j))};
function ga(a,b,c){return new Promise(function(d){var e=aa(a.win,function(f){var g=R(f.data);if(g&&f.origin===c&&f.source===b&&"__AMPHTML__"==g.app&&"handshake-poll"==g.name){if(a.j&&(!f.ports||!f.ports.length))throw Error("Did not receive communication port from the Viewer!");f=f.ports&&0<f.ports.length?f.ports[0]:new S(a.win,c,a.win.parent);d(f);e()}})})}function Z(a,b,c,d,e){var f=c.getUrl(),g=B(f);return e.sendRequest("channelOpen",q({url:f,sourceUrl:g}),!0).then(function(){ha(a,e,b,d)})}
function ha(a,b,c,d){b.setDefaultHandler(function(a,b,d){return c.receiveMessage(a,b,d)});c.setMessageDeliverer(b.sendRequest.bind(b),d);ba(a.win,a.K.bind(a,b));c.hasCapability("swipe")&&new N(a.win,b)}Y.prototype.K=function(a){return a.sendRequest("unloaded",{},!0)};(function(a){(new Y(a.win)).init()})(self.AMP);
})});
//# sourceMappingURL=amp-viewer-integration-0.1.js.map

