(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"1525381599226",f:(function(AMP){var v;function ba(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}var ca=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a}(this);function da(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ea=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function fa(a){var b=Object.create(null);if(!a)return b;for(var c;c=ea.exec(a);){var d=da(c[1],c[1]),e=c[2]?da(c[2],c[2]):"";b[d]=e}return b};var ga="";function E(){var a,b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;var d=fa(c.location.originalHash||c.location.hash),e=fa(c.location.search);ga||(ga=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011525381599226");c=b.AMP_MODE={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,geoOverride:d["amp-geo"],minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"1525381599226",rtvVersion:ga}}return c};var ha=Object.prototype.toString;function ja(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b}function ka(a){return"[object Object]"===ha.call(a)};function la(a){var b=a.message,c=String(Math.random());a.message=c;if(a.message===c)return a.message=b,a;var b=Error(a.message),d;for(d in a)b[d]=a[d];b.stack=a.stack;return b}function ra(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=la(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function sa(a){var b=ra.apply(null,arguments);setTimeout(function(){self.reportError(b);throw b;})}self.log=self.log||{user:null,dev:null,userForEmbed:null};
var ta=self.log;function I(){if(!ta.user)throw Error("failed to call initLogConstructor");return ta.user}function ua(){if(ta.dev)return ta.dev;throw Error("failed to call initLogConstructor");};var va=Object.prototype.hasOwnProperty;function J(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function wa(a){return a||{}}function xa(a,b){if(va.call(a,b))return a[b]}
function ya(a,b){var c=10,c=void 0===c?10:c,d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.t=b.t;a.s=b.s;a.d=b.d;if(d.includes(a.s))throw Error("Source object has a circular reference.");d.push(a.s);a.t!==a.s&&(a.d>c?Object.assign(a.t,a.s):(Object.keys(a.s).forEach(function(a){return function(b){var c=a.s[b];if(va.call(a.t,b)){var d=a.t[b];if(ka(c)&&ka(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(a)),a={s:a.s,t:a.t,d:a.d}))}};function za(a){this.qa=a;this.J=Object.create(null)}za.prototype.get=function(a){if(this.J[a])return this.J[a].access=Date.now(),this.J[a].payload};za.prototype.put=function(a,b){var c=this;this.J[a]={payload:b,access:Date.now()};var d=Object.keys(this.J);d.length>this.qa&&(ua().warn("lru-cache","Trimming template cache"),d.sort(function(a,b){return c.J[b].access-c.J[a].access}),delete this.J[d[d.length-1]])};function R(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var Ga=self.AMP_CONFIG||{},Ha=Ga.cdnUrl||"https://cdn.ampproject.org",Ia=("string"==typeof Ga.cdnProxyRegex?new RegExp(Ga.cdnProxyRegex):Ga.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,Ja=Ga.errorReportingUrl||"https://amp-error-reporting.appspot.com/r";var Ka=wa({c:!0,v:!0,a:!0,ad:!0}),La,Ma,Na=/[?&]amp_js[^&]*/,Oa=/[?&]usqp[^&]*/;
function S(a){var b;La||(La=self.document.createElement("a"),Ma=self.UrlCache||(self.UrlCache=new za(100)));var c=Ma.get(a);if(c)return c;var d=La;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var f=e,g=f;if(b)return g;Ma.put(a,g);return g}function Pa(a){"string"==typeof a&&(a=S(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function Qa(a,b){var c;c=void 0===c?"source":c;I().assert(null!=a,"%s %s must be available",b,c);var d=a;I().assert(Pa(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d);return d}function Ra(a){"string"==typeof a&&(a=S(a));return Ia.test(a.origin)}
function Sa(a){"string"==typeof a&&(a=S(a));if(!Ra(a))return a.href;var b=a.pathname.split("/"),c=b[1];I().assert(Ka[c],"Unknown path prefix in url %s",a.href);var d=b[2],e="s"==d?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(d);I().assert(0<e.indexOf("."),"Expected a . in origin %s",e);b.splice(1,"s"==d?3:2);b=e+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(Na,"").replace(Oa,"").replace(/^[?&]/,""))?"?"+c:"":"";return b+c+(a.hash||"")}
function Ta(a,b){"string"==typeof b&&(b=S(b));var c;if("function"==typeof URL)c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=S(d));c=c.replace(/\\/g,"/");var e=S(c);c=R(c.toLowerCase(),e.protocol)?e.href:R(c,"//")?d.protocol+c:R(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Ua(a){var b=S(a),c=fa(b.search);I().assert(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function Va(a,b){try{return JSON.parse(a)}catch(c){b&&b(c)}}
function Wa(a,b,c){c=void 0===c?3:c;if(!isFinite(c))throw Error("depth arg must be finite: "+c);if(a===b)return!0;if(1>c||typeof a!==typeof b)return!1;if(Array.isArray(a)&&Array.isArray(b)){if(a.length!==b.length)return!1;for(var d=0;d<a.length;d++)if(!Wa(a[d],b[d],c-1))return!1;return!0}if(a&&b&&"object"===typeof a&&"object"===typeof b){var e=Object.keys(a),f=Object.keys(b);if(e.length!==f.length)return!1;for(d=0;d<e.length;d++){var g=e[d],h=a[g],k=b[g];if(!Wa(h,k,c-1))return!1}return!0}return!1}
;function Xa(a,b,c){if(a.nodeType){var d=Ya((a.ownerDocument||a).defaultView,b);if(d)return d}return!a.nodeType||c?T(a,b):null}function bb(a,b){var c=cb(a);Ya(a,"bind");db(a,a,"bind",function(){return b});eb(a,"bind")}function Ya(a,b){var c=cb(a);return a!=c&&fb(a,b)?eb(a,b):null}function U(a,b){a=cb(a);return eb(a,b)}function T(a,b){a=gb(a);a=hb(a);return eb(a,b)}function cb(a){return a.__AMP_TOP||a}function gb(a){return a.nodeType?U((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function hb(a){a=gb(a);return a.isSingleDoc()?a.win:a}function eb(a,b){fb(a,b);var c=ib(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function db(a,b,c,d){var e=ib(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=d,f.context=b,f.resolve&&eb(a,c))}
function jb(a,b){var c=kb(a,b);if(c)return c;var d,e=new Promise(function(a){d=a});ib(a)[b]={obj:null,promise:e,resolve:d,context:null,ctor:null};return e}function kb(a,b){var c=ib(a)[b];if(c){if(c.promise)return c.promise;eb(a,b);return c.promise=Promise.resolve(c.obj)}return null}function ib(a){var b=a.services;b||(b=a.services={});return b}function fb(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function lb(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function mb(a,b){lb(a.documentElement,function(){return!!a.body},b)}function nb(a){return new Promise(function(b){mb(a,b)})}
function ob(a){var b;return(b="function"===typeof a.getElementsByTagName?a.getElementsByTagName("title"):a.querySelectorAll("title"))&&b[0]||null}function pb(a,b){for(var c=0,d;void 0!==(d=a[c]);c++)b(d,c)}function qb(a){return"SCRIPT"==a.tagName&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function rb(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-bind"]:!1}function sb(a){var b=gb(a),c=kb(hb(a),"bind");return c?c:Promise.resolve().then(function(){return rb(b.win)?jb(hb(a),"bind"):b.whenBodyAvailable().then(function(){return rb(b.win)?jb(hb(a),"bind"):null})})}function tb(a){var b=Xa(a,"bind");if(b)return Promise.resolve(b);if(a.nodeType){var b=(a.ownerDocument||a).defaultView,c=cb(b);return b!==c?ub(b):sb(a)}return Promise.resolve(null)}
function ub(a){return Promise.resolve().then(function(){return rb(a)?jb(a,"bind"):nb(a.document).then(function(){return rb(a)?jb(a,"bind"):null})})};function vb(){var a=wb();return function(b){return setTimeout(b,a())}}function wb(){var a=0;return function(){var b=Math.pow(1.5,a++),c;c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var xb,yb="Webkit webkit Moz moz ms O o".split(" ");function zb(a,b){var c=void 0;if(R(b,"--"))return b;xb||(xb=J());var d=xb[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<yb.length;f++){var g=yb[f]+e;if(void 0!==a[g]){e=g;break a}}e=""}var h=e;void 0!==a[h]&&(d=h)}c||(xb[b]=d)}return d}function Ab(a,b,c){var d;(b=zb(a.style,b))&&(a.style[b]=d?c+d:c)}
function Bb(a){var b=!1;if(void 0===b){var c;c=(c=zb(a.style,"display"))?a.style[c]:void 0;b="none"==c}Ab(a,"display",b?"":"none")};var Cb={"amp-dynamic-css-classes":"[custom-element=amp-dynamic-css-classes]",variant:"amp-experiment","amp-story":"amp-story[standalone]"};function Db(a){var b=Hb(a).map(function(b){return U(a,"timer").timeoutPromise(3E3,jb(a,b),"Render timeout waiting for service "+b+" to be ready.")});return Promise.all(b)}function Hb(a){var b=a.document;return Object.keys(Cb).filter(function(a){return b.querySelector(Cb[a])})};function Ib(a){var b,c=a.defaultView;if(!c.__AMP_BODY_VISIBLE){var d=function(){c.__AMP_BODY_VISIBLE=!0;var b=a.body,d={opacity:1,visibility:"visible",animation:"none"},g;for(g in d)Ab(b,g,d[g]);try{T(a,"resources").renderStarted()}catch(h){}};try{mb(a,function(){c.__AMP_BODY_VISIBLE||(c.__AMP_BODY_VISIBLE=!0,b?Db(c).catch(function(a){sa(a);return[]}).then(function(b){d();0<b.length&&T(a,"resources").schedulePass(1,!0);try{var e=U(c,"performance");e.tick("mbv");e.flush()}catch(g){}}):d())})}catch(e){d(),
sa(e)}}};var Jb=self.AMPErrors||[];self.AMPErrors=Jb;function Kb(a){Kb=vb();return Kb(a)}function Lb(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var Mb;
function V(a,b){try{var c;if(a)if(void 0!==a.message)a=la(a),c=!0;else{var d=a;a=Error(Lb(d));a.origError=d}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var e=b||a.associatedElement;e&&e.classList&&(e.classList.add("i-amphtml-error"),E().development&&(e.classList.add("i-amphtml-element-error"),e.setAttribute("error-message",a.message)));if(self.console){var f=console.error||console.log;a.messageArray?f.apply(console,a.messageArray):e?f.call(console,a.message,e):f.call(console,a.message)}e&&
e.sa&&e.sa("amp:error",a.message);Nb.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(g){setTimeout(function(){throw g;})}}function Nb(a,b,c,d,e){this&&this.document&&Ib(this.document);if(!E().development){var f=!1;try{f=Ob()}catch(h){}if(!(f&&.01<Math.random())){var g=Pb(a,b,c,d,e,f);g&&(Qb(this,g),Kb(function(){var a=new XMLHttpRequest;a.open("POST",Ja,!0);a.send(JSON.stringify(g))}))}}}
function Qb(a,b){var c=U(a,"ampdoc");if(c.isSingleDoc()){var d=c.getAmpDoc(),e=d.getRootNode().documentElement,f=e.hasAttribute("report-errors-to-viewer");if(f){var g=T(d,"viewer");g.hasCapability("errorReporter")?g.isTrustedViewer().then(function(a){if(!a)return!1;g.sendMessage("error",b);return!0}):Promise.resolve(!1)}else Promise.resolve(!1)}else Promise.resolve(!1)}
function Pb(a,b,c,d,e,f){var g=!1;e&&(a=e.message?e.message:String(e),e.expected&&(g=!0));a||(a="Unknown error");if(!/_reported_/.test(a)&&"CANCELLED"!=a){var h=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a)if(g=!0,.001<h)return;var k=0<=a.indexOf("\u200b\u200b\u200b");if(!(k&&.1<h)){var l=Object.create(null);l.v=E().rtvVersion;l.noAmp=f?"1":"0";l.m=a.replace("\u200b\u200b\u200b","");l.a=k?"1":"0";l.ex=g?"1":"0";var p="1p";self.context&&self.context.location?(l["3p"]="1",p=
"3p"):E().runtime&&(p=E().runtime);l.rt=p;f=self;l.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;l.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(l.or=self.location.ancestorOrigins[0]);self.viewerState&&(l.vs=self.viewerState);self.parent&&self.parent!=self&&(l.iem="1");if(self.AMP&&self.AMP.viewer){var r=self.AMP.viewer.getResolvedViewerUrl(),q=self.AMP.viewer.maybeGetMessagingOrigin();r&&(l.rvu=r);q&&(l.mso=
q)}Mb||(Mb=Rb());l.jse=Mb;var u=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var w in f)u.push(w+"="+(f[w]?"1":"0"));l.exps=u.join(",");e?(l.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(l.args=JSON.stringify(e.args)),k||e.ignoreStack||!e.stack||(l.s=e.stack),e.message+=" _reported_"):(l.f=b||"",l.l=c||"",l.c=d||"");l.r=self.document.referrer;l.ae=Jb.join(",");l.fr=self.location.originalHash||self.location.hash;25<=Jb.length&&Jb.splice(0,Jb.length-25+1);Jb.push(a);return l}}}
function Ob(){for(var a=self.document.querySelectorAll("script[src]"),b=0;b<a.length;b++)if(!Ra(a[b].src.toLowerCase()))return!0;return!1}function Rb(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(e){var c=e.stack;if(R(c,"t@"))return"Safari";if(-1<c.indexOf(".prototype.t@"))return"Firefox";var d=c.split("\n").pop();if(/\bat .* \(/i.test(d))return"IE";if(R(c,"Error: message"))return"Chrome"}return"unknown"};function Sb(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?(d<e&&(a[d]=f),d++):c.push(f)}d<a.length&&(a.length=d)};function Tb(a){return AMP.BaseElement.apply(this,arguments)||this}ba(Tb,AMP.BaseElement);v=Tb.prototype;v.getLayoutPriority=function(){return 1};v.isAlwaysFixed=function(){return!0};v.isLayoutSupported=function(){return!0};v.renderOutsideViewport=function(){return!0};v.O=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};function Ub(a,b,c){var d=void 0,d=void 0===d?".":d;c=void 0===c?0:c;var e=Qa(b.getAttribute("src"),b),f=Xa(a,"url-replace",!0),g=1<=c?f.expandUrlAsync(e):Promise.resolve(e);return g.then(function(d){1==c&&f.collectUnwhitelistedVars(b).then(function(a){if(0<a.length){var c=b.tagName;I().error(c,"URL variable substitutions in CORS fetches triggered by amp-bind will soon require opt-in. Please add "+('data-amp-replace="'+a.join(" ")+'" to the ')+("<"+c+'> element. See "bit.ly/amp-var-subs" for details.'));
ua().expectedError(c,"amp-bind CORS fetch without opt-in!")}});var e={};b.hasAttribute("credentials")?e.credentials=b.getAttribute("credentials"):e.requireAmpResponseSourceOrigin=!1;return U(a.win,"batched-xhr").fetchJson(d,e)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");var b;b=d||".";if("."!=b){b=b.split(".");for(var c=0;c<b.length;c++){var e=b[c];if(e&&a&&void 0!==a[e]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,
e)))a=a[e];else{a=void 0;break}}}b=a;return b})};function Vb(a){return AMP.BaseElement.apply(this,arguments)||this}ba(Vb,AMP.BaseElement);v=Vb.prototype;v.getLayoutPriority=function(){return 1};v.isAlwaysFixed=function(){return!0};v.isLayoutSupported=function(){return!0};v.activate=function(){var a=this.O();this.user().error(a,'Please use AMP.setState() action explicitly, e.g. on="submit-success:AMP.setState({myAmpState: event.response})"')};
v.buildCallback=function(){var a=this;Bb(this.element);this.element.setAttribute("aria-hidden","true");T(this.getAmpDoc(),"viewer").whenFirstVisible().then(function(){return a.Y()})};v.mutatedAttributesCallback=function(a){if(T(this.getAmpDoc(),"viewer").isVisible())void 0!==a.src&&Wb(this,!1);else{var b=this.O();ua().error(b,"Viewer must be visible before mutation.")}};v.renderOutsideViewport=function(){return!0};
v.Y=function(){var a=this;this.element.hasAttribute("overridable")&&tb(this.element).then(function(b){b.makeStateKeyOverridable(a.element.getAttribute("id"))});0<this.element.children.length&&Xb(this);this.element.hasAttribute("src")&&Wb(this,!0)};
function Xb(a){var b=a.O(),c=a.element.children;if(1!=c.length)a.user().error(b,"Should contain exactly one <script> child.");else{var d=c[0];qb(d)?(c=Va(d.textContent,function(c){a.user().error(b,"Failed to parse state. Is it valid JSON?",c)}),Yb(a,c,!0)):a.user().error(b,'State should be in a <script> tag with type="application/json".')}}function Zb(a,b,c){var d=b.getAttribute("src"),e=1;if(c||S(Sa(d)).origin==S(Sa(a.win.location)).origin)e=2;return Ub(a,b,e)}
function Wb(a,b){var c=a.getAmpDoc();Zb(c,a.element,b).then(function(c){Yb(a,c,b)})}function Yb(a,b,c){if(void 0!==b&&null!==b){var d=I().assert(a.element.id,"<amp-state> must have an id."),e=J();e[d]=b;tb(a.element).then(function(a){a.setState(e,c,!c)})}}v.O=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};function Y(a,b,c){this.type=a;this.args=b;this.value=c};(function(){function a(a,b,c){var d;c=c||{};for(d=a.length;d--;c[a[d]]=b);return c}function b(){this.yy={}}var c=[1,7],d=[1,10],e=[1,11],f=[1,12],g=[1,13],h=[1,23],k=[1,17],l=[1,18],p=[1,19],r=[1,20],q=[1,21],u=[1,22],w=[1,26],A=[1,25],y=[1,27],F=[1,28],z=[1,29],C=[1,30],D=[1,31],L=[1,32],G=[1,33],K=[1,34],H=[1,35],M=[1,36],P=[1,37],Q=[1,38],B=[1,39],x=[1,41],t=[5,10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,31,35,38,39,49],ma=[2,39],na=[1,47],Ba=[1,52],ia=[1,54],W=[5,10,14,15,16,17,18,19,20,21,
22,23,24,25,26,27,28,35,39,49],Ca=[1,75],oa=[35,49],Da=[10,35,39],Ea=[5,10,14,15,19,20,21,22,23,24,25,26,27,28,35,39,49],aa=[5,10,19,20,21,22,23,24,25,26,27,28,35,39,49],pa=[5,10,19,20,25,26,27,28,35,39,49],Fa=[10,35],qa={trace:function O(){},yy:{},xa:{error:2,result:3,expr:4,EOF:5,operation:6,invocation:7,member_access:8,"(":9,")":10,variable:11,literal:12,"!":13,"-":14,"+":15,"*":16,"/":17,"%":18,"&&":19,"||":20,"<=":21,"<":22,">=":23,">":24,"!=":25,"==":26,"?":27,":":28,NAME:29,args:30,".":31,
arrow_function:32,"=>":33,params:34,",":35,array:36,member:37,"[":38,"]":39,primitive:40,object_literal:41,array_literal:42,STRING:43,NUMBER:44,TRUE:45,FALSE:46,NULL:47,"{":48,"}":49,object:50,key_value:51,key:52,$accept:0,$end:1},T:{2:"error",5:"EOF",9:"(",10:")",13:"!",14:"-",15:"+",16:"*",17:"/",18:"%",19:"&&",20:"||",21:"<=",22:"<",23:">=",24:">",25:"!=",26:"==",27:"?",28:":",29:"NAME",31:".",33:"=>",35:",",38:"[",39:"]",43:"STRING",44:"NUMBER",45:"TRUE",46:"FALSE",47:"NULL",48:"{",49:"}"},ka:[0,
[3,2],[3,1],[4,1],[4,1],[4,1],[4,3],[4,1],[4,1],[6,2],[6,2],[6,2],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,5],[7,2],[7,4],[7,6],[32,4],[32,3],[32,5],[34,3],[34,3],[30,2],[30,3],[8,2],[37,2],[37,3],[11,1],[12,1],[12,1],[12,1],[40,1],[40,1],[40,1],[40,1],[40,1],[42,2],[42,3],[42,4],[36,1],[36,3],[41,2],[41,3],[41,4],[50,1],[50,3],[51,3],[52,1],[52,1],[52,3]],performAction:function Aa(a,b,c,d,e,n){var m=n.length-1;switch(e){case 1:return n[m-1];case 2:return"";
case 3:case 4:case 5:case 7:case 8:this.h=n[m];break;case 6:this.h=n[m-1];break;case 9:this.h=new Y(12,[n[m]]);break;case 10:this.h=new Y(13,[n[m]]);break;case 11:this.h=new Y(14,[n[m]]);break;case 12:this.h=new Y(15,[n[m-2],n[m]]);break;case 13:this.h=new Y(16,[n[m-2],n[m]]);break;case 14:this.h=new Y(17,[n[m-2],n[m]]);break;case 15:this.h=new Y(18,[n[m-2],n[m]]);break;case 16:this.h=new Y(19,[n[m-2],n[m]]);break;case 17:this.h=new Y(20,[n[m-2],n[m]]);break;case 18:this.h=new Y(21,[n[m-2],n[m]]);
break;case 19:this.h=new Y(22,[n[m-2],n[m]]);break;case 20:this.h=new Y(23,[n[m-2],n[m]]);break;case 21:this.h=new Y(24,[n[m-2],n[m]]);break;case 22:this.h=new Y(25,[n[m-2],n[m]]);break;case 23:this.h=new Y(26,[n[m-2],n[m]]);break;case 24:this.h=new Y(27,[n[m-2],n[m]]);break;case 25:this.h=new Y(28,[n[m-4],n[m-2],n[m]]);break;case 26:this.h=new Y(1,[void 0,n[m]],n[m-1]);break;case 27:this.h=new Y(1,[n[m-3],n[m]],n[m-1]);break;case 28:this.h=new Y(1,[n[m-5],n[m-1]],n[m-3]);break;case 29:this.h=new Y(29,
[void 0,n[m]]);break;case 30:var f=new Y(6,null,[n[m-2]]);this.h=new Y(29,[f,n[m]]);break;case 31:this.h=new Y(29,[n[m-3],n[m]]);break;case 32:this.h=new Y(6,null,[n[m-2],n[m]]);break;case 33:this.h=n[m-2];this.h.value.push(n[m]);break;case 34:this.h=new Y(2,[]);break;case 35:this.h=new Y(2,[n[m-1]]);break;case 36:this.h=new Y(3,[n[m-1],n[m]]);break;case 37:this.h=new Y(4,null,n[m]);break;case 38:this.h=new Y(4,[n[m-1]]);break;case 39:this.h=new Y(5,null,n[m]);break;case 40:case 41:case 42:case 60:this.h=
n[m];break;case 43:n=a.substr(1,b-2);this.h=new Y(6,null,n);break;case 44:this.h=new Y(6,null,Number(a));break;case 45:this.h=new Y(6,null,!0);break;case 46:this.h=new Y(6,null,!1);break;case 47:this.h=new Y(6,null,null);break;case 48:this.h=new Y(7,[]);break;case 49:this.h=new Y(7,[n[m-1]]);break;case 50:this.h=new Y(7,[n[m-2]]);break;case 51:this.h=new Y(8,[n[m]]);break;case 52:case 57:this.h=n[m-2];this.h.args.push(n[m]);break;case 53:this.h=new Y(9,[]);break;case 54:this.h=new Y(9,[n[m-1]]);break;
case 55:this.h=new Y(9,[n[m-2]]);break;case 56:this.h=new Y(10,[n[m]]);break;case 58:this.h=new Y(11,[n[m-2],n[m]]);break;case 59:this.h=new Y(6,null,n[m]);break;case 61:this.h=n[m-1]}},table:[{3:1,4:2,5:[1,3],6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{1:[3]},{5:[1,24],14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,37:40,38:x},{1:[2,2]},a(t,[2,3]),a(t,[2,4]),a(t,[2,5]),{4:42,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,
29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},a(t,[2,7]),a(t,[2,8]),{4:43,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:44,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:45,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},a(t,ma,{30:46,9:na}),a(t,[2,40]),a(t,[2,41]),a(t,[2,42]),a(t,[2,43]),a(t,[2,44]),a(t,[2,45]),a(t,[2,46]),
a(t,[2,47]),{29:Ba,38:ia,40:53,43:k,44:l,45:p,46:r,47:q,49:[1,48],50:49,51:50,52:51},{4:57,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,36:56,38:h,39:[1,55],40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{1:[2,1]},{4:58,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:59,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:60,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,
43:k,44:l,45:p,46:r,47:q,48:u},{4:61,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:62,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:63,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:64,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:65,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,
29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:66,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:67,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:68,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:69,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:70,6:4,7:5,8:6,
9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:71,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{29:[1,72]},a(t,[2,36]),{4:73,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{10:[1,74],14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,37:40,38:x},a(W,[2,9],{37:40,31:B,38:x}),a(W,[2,10],{37:40,31:B,38:x}),a(W,[2,11],{37:40,31:B,
38:x}),a(t,[2,26]),{4:57,6:4,7:5,8:6,9:c,10:Ca,11:8,12:9,13:d,14:e,15:f,29:g,36:76,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},a(t,[2,53]),{35:[1,78],49:[1,77]},a(oa,[2,56]),{28:[1,79]},{28:[2,59]},{28:[2,60]},{4:80,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},a(t,[2,48]),{35:[1,82],39:[1,81]},a(Da,[2,51],{37:40,14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,38:x}),a(Ea,[2,12],{37:40,16:y,17:F,18:z,31:B,38:x}),
a(Ea,[2,13],{37:40,16:y,17:F,18:z,31:B,38:x}),a(W,[2,14],{37:40,31:B,38:x}),a(W,[2,15],{37:40,31:B,38:x}),a(W,[2,16],{37:40,31:B,38:x}),a([5,10,19,20,27,28,35,39,49],[2,17],{37:40,14:w,15:A,16:y,17:F,18:z,21:L,22:G,23:K,24:H,25:M,26:P,31:B,38:x}),a([5,10,20,27,28,35,39,49],[2,18],{37:40,14:w,15:A,16:y,17:F,18:z,19:C,21:L,22:G,23:K,24:H,25:M,26:P,31:B,38:x}),a(aa,[2,19],{37:40,14:w,15:A,16:y,17:F,18:z,31:B,38:x}),a(aa,[2,20],{37:40,14:w,15:A,16:y,17:F,18:z,31:B,38:x}),a(aa,[2,21],{37:40,14:w,15:A,
16:y,17:F,18:z,31:B,38:x}),a(aa,[2,22],{37:40,14:w,15:A,16:y,17:F,18:z,31:B,38:x}),a(pa,[2,23],{37:40,14:w,15:A,16:y,17:F,18:z,21:L,22:G,23:K,24:H,31:B,38:x}),a(pa,[2,24],{37:40,14:w,15:A,16:y,17:F,18:z,21:L,22:G,23:K,24:H,31:B,38:x}),{14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,28:[1,83],31:B,37:40,38:x},a(t,[2,37],{30:84,9:[1,85]}),{14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,37:40,38:x,39:[1,86]},a(t,[2,6]),a(t,[2,34]),{10:[1,87],35:[1,88]},
a(t,[2,54]),{29:Ba,38:ia,40:53,43:k,44:l,45:p,46:r,47:q,49:[1,89],51:90,52:51},{4:91,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,37:40,38:x,39:[1,92]},a(t,[2,49]),{4:94,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,39:[1,93],40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:95,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,
46:r,47:q,48:u},a(t,[2,27]),{4:57,6:4,7:5,8:6,9:[1,97],10:Ca,11:8,12:9,13:d,14:e,15:f,29:[1,98],32:96,36:76,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},a(t,[2,38]),a(t,[2,35]),{4:94,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},a(t,[2,55]),a(oa,[2,57]),a(oa,[2,58],{37:40,14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,38:x}),{28:[2,61]},a(t,[2,50]),a(Da,[2,52],{37:40,14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,
22:G,23:K,24:H,25:M,26:P,27:Q,31:B,38:x}),a([5,10,28,35,39,49],[2,25],{37:40,14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,38:x}),{10:[1,99]},{4:42,6:4,7:5,8:6,9:c,10:[1,100],11:8,12:9,13:d,14:e,15:f,29:[1,102],34:101,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},a([10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,31,35,38],ma,{30:46,9:na,33:[1,103]}),a(t,[2,28]),{33:[1,104]},{10:[1,105],35:[1,106]},a([10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,31,38],ma,{30:46,
9:na,35:[1,107]}),{4:108,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{4:109,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},{33:[1,110]},{29:[1,111]},{29:[1,112]},{10:[2,30],14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,37:40,38:x},{10:[2,29],14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,37:40,38:x},{4:113,6:4,7:5,8:6,9:c,11:8,12:9,13:d,
14:e,15:f,29:g,38:h,40:14,41:15,42:16,43:k,44:l,45:p,46:r,47:q,48:u},a(Fa,[2,33]),a(Fa,[2,32]),{10:[2,31],14:w,15:A,16:y,17:F,18:z,19:C,20:D,21:L,22:G,23:K,24:H,25:M,26:P,27:Q,31:B,37:40,38:x}],defaultActions:{3:[2,2],24:[2,1],52:[2,59],53:[2,60],92:[2,61]},parseError:function Fb(a,b){if(b.recoverable)this.trace(a);else throw a=Error(a),a.hash=b,a;},parse:function N(a){function b(a){d.length-=2*a;m.length-=a;f.length-=a}var c=this,d=[0],e=[],m=[null],f=[],y=this.table,g="",k=0,h=0,l=0,F=2,p=1,z=f.slice.call(arguments,
1),q=Object.create(this.lexer),r={yy:{}},C;for(C in this.yy)Object.prototype.hasOwnProperty.call(this.yy,C)&&(r.yy[C]=this.yy[C]);q.setInput(a,r.yy);r.yy.lexer=q;r.yy.parser=this;"undefined"==typeof q.yylloc&&(q.yylloc={});var u=q.yylloc;f.push(u);var L=q.options&&q.options.ranges;this.parseError="function"===typeof r.yy.parseError?r.yy.parseError:Object.getPrototypeOf(this).parseError;var w=function(){var a;a=q.lex()||p;"number"!==typeof a&&(a=c.xa[a]||a);return a};for(var D,A,t,G={},B,x,K,H;;){C=
d[d.length-1];if(this.defaultActions[C])t=this.defaultActions[C];else{if(null===D||"undefined"==typeof D)D=w();t=y[C]&&y[C][D]}if("undefined"===typeof t||!t.length||!t[0]){var M="";H=[];for(B in y[C])this.T[B]&&B>F&&H.push("'"+this.T[B]+"'");M=q.showPosition?"Parse error on line "+(k+1)+":\n"+q.showPosition()+"\nExpecting "+H.join(", ")+", got '"+(this.T[D]||D)+"'":"Parse error on line "+(k+1)+": Unexpected "+(D==p?"end of input":"'"+(this.T[D]||D)+"'");this.parseError(M,{text:q.match,token:this.T[D]||
D,line:q.yylineno,loc:u,expected:H})}if(t[0]instanceof Array&&1<t.length)throw Error("Parse Error: multiple actions possible at state: "+C+", token: "+D);switch(t[0]){case 1:d.push(D);m.push(q.yytext);f.push(q.yylloc);d.push(t[1]);D=null;A?(D=A,A=null):(h=q.yyleng,g=q.yytext,k=q.yylineno,u=q.yylloc,0<l&&l--);break;case 2:x=this.ka[t[1]][1];G.h=m[m.length-x];G.ba={first_line:f[f.length-(x||1)].first_line,last_line:f[f.length-1].last_line,first_column:f[f.length-(x||1)].first_column,last_column:f[f.length-
1].last_column};L&&(G.ba.range=[f[f.length-(x||1)].range[0],f[f.length-1].range[1]]);C=this.performAction.apply(G,[g,h,k,r.yy,t[1],m,f].concat(z));if("undefined"!==typeof C)return C;x&&(d=d.slice(0,-2*x),m=m.slice(0,-1*x),f=f.slice(0,-1*x));d.push(this.ka[t[1]][0]);m.push(G.h);f.push(G.ba);K=y[d[d.length-2]][d[d.length-1]];d.push(K);break;case 3:return!0}}}},ab=function(){return{EOF:1,parseError:function(a,b){if(this.yy.parser)this.yy.parser.parseError(a,b);else throw Error(a);},setInput:function(a,
b){this.yy=b||this.yy||{};this._input=a;this._more=this._backtrack=this.done=!1;this.yylineno=this.yyleng=0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};this.options.ranges&&(this.yylloc.range=[0,0]);this.offset=0;return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.offset++;this.match+=a;this.matched+=a;var b=a.match(/(?:\r\n?|\n).*/g);b?(this.yylineno++,this.yylloc.last_line++):
this.yylloc.last_column++;this.options.ranges&&this.yylloc.range[1]++;this._input=this._input.slice(1);return a},unput:function(a){var b=a.length,c=a.split(/(?:\r\n?|\n)/g);this._input=a+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-b);this.offset-=b;var d=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);c.length-1&&(this.yylineno-=c.length-1);a=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,
last_line:this.yylineno+1,first_column:this.yylloc.first_column,last_column:c?(c.length===d.length?this.yylloc.first_column:0)+d[d.length-c.length].length-c[0].length:this.yylloc.first_column-b};this.options.ranges&&(this.yylloc.range=[a[0],a[0]+this.yyleng-b]);this.yyleng=this.yytext.length;return this},more:function(){this._more=!0;return this},reject:function(){if(this.options.backtrack_lexer)this._backtrack=!0;else return this.parseError("Lexical error on line "+(this.yylineno+1)+". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n"+
this.showPosition(),{text:"",token:null,line:this.yylineno});return this},less:function(a){this.unput(this.match.slice(a))},pastInput:function(){var a=this.matched.substr(0,this.matched.length-this.match.length);return(20<a.length?"...":"")+a.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var a=this.match;20>a.length&&(a+=this._input.substr(0,20-a.length));return(a.substr(0,20)+(20<a.length?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),b=Array(a.length+1).join("-");
return a+this.upcomingInput()+"\n"+b+"^"},test_match:function(a,b){var c,d;this.options.backtrack_lexer&&(d={yylineno:this.yylineno,yylloc:{first_line:this.yylloc.first_line,last_line:this.last_line,first_column:this.yylloc.first_column,last_column:this.yylloc.last_column},yytext:this.yytext,match:this.match,matches:this.matches,matched:this.matched,yyleng:this.yyleng,offset:this.offset,_more:this._more,_input:this._input,yy:this.yy,conditionStack:this.conditionStack.slice(0),done:this.done},this.options.ranges&&
(d.yylloc.range=this.yylloc.range.slice(0)));if(c=a[0].match(/(?:\r\n?|\n).*/g))this.yylineno+=c.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:c?c[c.length-1].length-c[c.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;this.options.ranges&&(this.yylloc.range=[this.offset,this.offset+=this.yyleng]);this._backtrack=
this._more=!1;this._input=this._input.slice(a[0].length);this.matched+=a[0];a=this.performAction.call(this,this.yy,this,b,this.conditionStack[this.conditionStack.length-1]);this.done&&this._input&&(this.done=!1);if(a)return a;if(this._backtrack)for(var e in d)this[e]=d[e];return!1},next:function(){if(this.done)return this.EOF;this._input||(this.done=!0);var a,b,c;this._more||(this.match=this.yytext="");for(var d=this._currentRules(),e=0;e<d.length;e++)if((b=this._input.match(this.rules[d[e]]))&&(!a||
b[0].length>a[0].length))if(a=b,c=e,this.options.backtrack_lexer){a=this.test_match(b,d[e]);if(!1!==a)return a;if(this._backtrack)a=!1;else return!1}else if(!this.options.flex)break;return a?(a=this.test_match(a,d[c]),!1!==a?a:!1):""===this._input?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();return a?a:this.lex()},begin:function(a){this.conditionStack.push(a)},
popState:function m(){return 0<this.conditionStack.length-1?this.conditionStack.pop():this.conditionStack[0]},_currentRules:function X(){return this.conditionStack.length&&this.conditionStack[this.conditionStack.length-1]?this.conditions[this.conditionStack[this.conditionStack.length-1]].rules:this.conditions.INITIAL.rules},topState:function Za(a){a=this.conditionStack.length-1-Math.abs(a||0);return 0<=a?this.conditionStack[a]:"INITIAL"},pushState:function n(a){this.begin(a)},stateStackSize:function $a(){return this.conditionStack.length},
options:{},performAction:function(a,b,c,d){var e=d;switch(c){case 1:return 47;case 2:return 45;case 3:return 46;case 4:return 44;case 5:return 29;case 6:return 43;case 7:return 43;case 8:return 33;case 9:return 15;case 10:return 14;case 11:return 16;case 12:return 17;case 13:return 19;case 14:return 20;case 15:return 25;case 16:return 26;case 17:return 21;case 18:return 22;case 19:return 23;case 20:return 24;case 21:return 13;case 22:return 27;case 23:return 28;case 24:return 18;case 25:return 38;
case 26:return 39;case 27:return 48;case 28:return 49;case 29:return 9;case 30:return 10;case 31:return 35;case 32:return 31;case 33:return"INVALID";case 34:return 5}},rules:[/^(?:\s+)/,/^(?:null\b)/,/^(?:true\b)/,/^(?:false\b)/,/^(?:[0-9]+(\.[0-9]+)?\b)/,/^(?:[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:'[^\']*')/,/^(?:"[^\"]*")/,/^(?:=>)/,/^(?:\+)/,/^(?:-)/,/^(?:\*)/,/^(?:\/)/,/^(?:&&)/,/^(?:\|\|)/,/^(?:!=)/,/^(?:==)/,/^(?:<=)/,/^(?:<)/,/^(?:>=)/,/^(?:>)/,/^(?:!)/,/^(?:\?)/,/^(?::)/,/^(?:%)/,/^(?:\[)/,/^(?:\])/,
/^(?:\{)/,/^(?:\})/,/^(?:\()/,/^(?:\))/,/^(?:,)/,/^(?:\.)/,/^(?:.)/,/^(?:$)/],conditions:{INITIAL:{rules:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34],inclusive:!0}}}}();qa.lexer=ab;b.prototype=qa;qa.Parser=b;return new b})();var $b=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function ac(a){for(var b=[],c;c=$b.exec(a);){var d=c[1],e=void 0,f;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new bc(b)}
function bc(a){I().assert(0<a.length,"Srcset must have at least one source");this.P=a;for(var b=!1,c=!1,d=0;d<a.length;d++)var e=a[d],b=b||!!e.width,c=c||!!e.dpr;I().assert(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?cc:dc);this.na=b;this.Ea=c}
bc.prototype.select=function(a,b){if(this.na){b*=a;a=this.P;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,h=Math.abs(g-b);if(h<=1.1*d||1.2<b/e)c=f,d=h,e=g;else break}}else for(a=this.P,c=0,d=Infinity,e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c;return this.P[b].url};bc.prototype.getUrls=function(){return this.P.map(function(a){return a.url})};
bc.prototype.stringify=function(a){for(var b=[],c=this.P,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.na?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function cc(a,b){I().assert(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function dc(a,b){I().assert(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var ec={"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},fc={width:null,height:null},gc={"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-IFRAME":{src:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,https:!0}},srcset:{alternativeName:"src"}},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null},"AMP-SELECTOR":{disabled:null,
selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-VIDEO":{alt:null,attribution:null,controls:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}}},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,http:!0,https:!0,mailto:!0,"fb-messenger":!0,intent:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},FIELDSET:{disabled:null},INPUT:{accept:null,accesskey:null,
autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|file|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SELECT:{autofocus:null,disabled:null,multiple:null,required:null,
size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null}},hc={src:!0,srcset:!0,href:!0};function ic(){}ic.prototype.canBind=function(a,b){return void 0!==jc(a,b)};
ic.prototype.isResultValid=function(a,b,c){var d=jc(a,b);d&&d.alternativeName&&(d=jc(a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&xa(hc,b)){var e;if("srcset"===b){var f;try{f=ac(c)}catch(l){return I().error("amp-bind","Failed to parse srcset: ",l),!1}e=f.getUrls()}else e=[c];for(a=0;a<e.length;a++){a:{var g=e[a];if((b=d.allowedProtocols)&&g&&(g=/^([^:\/?#.]+):[\s\S]*$/.exec(g),null!==g&&(g=g[1].toLowerCase().trim(),!b.hasOwnProperty(g)))){b=!1;break a}b=!0}if(!b)return!1}}var h=
d.blacklistedValueRegex;if(c&&h){var k=new RegExp(h,"i");if(k.test(c))return!1}return!0};function jc(a,b){if(R(b,"aria-"))return null;var c=xa(ec,b);if(void 0!==c)return c;var d=xa(fc,b);if(R(a,"AMP-")&&void 0!==d)return d;var e=xa(gc,a);if(e)return e[b]};function kc(){this.C=[]}kc.prototype.peek=function(){var a=this.C.length;return a?this.C[a-1].item:null};kc.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=b,d=-1,e=0,f=this.C.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.C.length)break;if(this.C[d].priority<c)e=d+1;else if(0<d&&this.C[d-1].priority>=c)f=d-1;else break}this.C.splice(d,0,{item:a,priority:b})};kc.prototype.dequeue=function(){return this.C.length?this.C.pop().item:null};
ca.Object.defineProperties(kc.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.C.length}}});var lc=/nochunking=1/.test(self.location.hash),mc=Promise.resolve();function nc(a,b){if(lc)mc.then(b);else{var c=oc,d=gb(a),e=hb(d);db(e,d,"chunk",c);T(a,"chunk").run(b,10)}}function pc(a){this.state="not_run";this.X=a}function qc(a,b){if("run"!=a.state){a.state="run";try{a.X(b)}catch(c){throw a.ia(c),c;}}}pc.prototype.O=function(){return this.X.displayName||this.X.name};pc.prototype.ia=function(){};pc.prototype.ha=function(){return!1};pc.prototype.ma=function(){return!0};
function rc(a,b,c){pc.call(this,a);var d=this;this.o=b;this.D=null;c.then(function(a){d.D=a;d.D.isVisible()&&qc(d,null);d.D.onVisibilityChanged(function(){d.D.isVisible()&&qc(d,null)})})}ba(rc,pc);rc.prototype.ia=function(){Ib(self.document)};rc.prototype.ha=function(){return this.D?this.D.isVisible():this.o.document.hidden?!1:!/visibilityState=(hidden|prerender)/.test(this.o.location.hash)};rc.prototype.ma=function(){return!!this.D};
function oc(a){var b=this;this.Da=a;this.o=a.win;this.S=new kc;this.da=this.ea.bind(this);this.Ba=jb(hb(a),"viewer");this.o.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.ea(null)})}oc.prototype.run=function(a,b){var c=new pc(a);sc(this,c,b)};oc.prototype.Ia=function(a){a=new rc(a,this.o,this.Ba);sc(this,a,Number.POSITIVE_INFINITY)};function sc(a,b,c){a.S.enqueue(b,c);mc.then(function(){tc(a)})}
function uc(a,b){for(var c=a.S.peek();c&&"not_run"!==c.state;)a.S.dequeue(),c=a.S.peek();c&&b&&a.S.dequeue();return c}oc.prototype.ea=function(a){var b=this,c=uc(this,!0);if(!c)return!1;var d=Date.now();qc(c,a);mc.then(function(){tc(b)});return!0};function vc(a){mc.then(function(){a.da(null)})}function tc(a){var b=uc(a);b&&(b.ha()?vc(a):b.ma()&&a.o.requestIdleCallback?wc(a.o,a.da):a.o.postMessage("amp-macro-task","*"))}
function wc(a,b){var c=15,d=2E3;function e(g){if(g.timeRemaining()<c){var h=d-(Date.now()-f);0>=h||g.didTimeout?b(g):a.requestIdleCallback(e,{timeout:h})}else b(g)}var f=Date.now();a.requestIdleCallback(e,{timeout:d})};function xc(a,b,c){var d="ww";a=b?a.protocol+"//"+a.host+"/dist":Ha;return c?a+"/rtv/"+E().rtvVersion+"/"+d+".js":a+"/"+d+".js"};function yc(a){var b=this;this.o=a;this.Ca=U(a,"xhr");var c=a.location,d=!1,e=!d,f=xc(c,d,e);this.aa=null;this.fa=this.Ca.fetchText(f,{ampCors:!1}).then(function(a){return a.text()}).then(function(c){c=new a.Blob([c],{type:"text/javascript"});var d=a.URL.createObjectURL(c);b.aa=new a.Worker(d);b.aa.onmessage=b.wa.bind(b)});this.V={};this.ra=0;this.oa=[a]}
function zc(a,b,c,d){return a.fa.then(function(){return new Promise(function(e,f){var g=a.ra++;a.V[g]={method:b,resolve:e,reject:f};e=d||a.o;f=a.oa.indexOf(e);e=0<=f?f:a.oa.push(e)-1;a.aa.postMessage({method:b,args:c,scope:e,id:g})})})}yc.prototype.wa=function(a){var b=a.data;a=b.method;var c=b.returnValue,b=b.id,d=this.V[b];d?(d.resolve(c),delete this.V[b]):ua().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};yc.prototype.hasPendingMessages=function(){return 0<Object.keys(this.V).length};
yc.prototype.Fa=function(){return this.fa};var Ac=function(){function a(a){var b=(""+a).match(u);return b?new k(l(b[1]),l(b[2]),l(b[3]),l(b[4]),l(b[5]),l(b[6]),l(b[7])):null}function b(a,b,f,g,l,h,q){a=new k(d(a,w),d(b,w),c(f),0<g?g.toString():null,d(l,A),null,c(q));h&&("string"===typeof h?a.setRawQuery(h.replace(/[^?&=0-9A-Za-z_\-~.%]/g,e)):a.setAllParameters(h));return a}function c(a){return"string"==typeof a?encodeURIComponent(a):null}function d(a,b){return"string"==typeof a?encodeURI(a).replace(b,e):null}function e(a){a=a.charCodeAt(0);
return"%"+"0123456789ABCDEF".charAt(a>>4&15)+"0123456789ABCDEF".charAt(a&15)}function f(a){return a.replace(/(^|\/)\.(?:\/|$)/g,"$1").replace(/\/{2,}/g,"/")}function g(a){if(null===a)return null;a=f(a);for(var b=r,c;(c=a.replace(b,"$1"))!=a;a=c);return a}function h(a,b){var c=a.clone(),d=b.hasScheme();d?c.setRawScheme(b.getRawScheme()):d=b.hasCredentials();d?c.setRawCredentials(b.getRawCredentials()):d=b.hasDomain();d?c.setRawDomain(b.getRawDomain()):d=b.hasPort();var e=b.getRawPath(),f=g(e);if(d)c.setPort(b.getPort()),
f=f&&f.replace(q,"");else if(d=!!e){if(47!==f.charCodeAt(0))var k=g(c.getRawPath()||"").replace(q,""),y=k.lastIndexOf("/")+1,f=g((y?k.substring(0,y):"")+g(e)).replace(q,"")}else f=f&&f.replace(q,""),f!==e&&c.setRawPath(f);d?c.setRawPath(f):d=b.hasQuery();d?c.setRawQuery(b.getRawQuery()):d=b.hasFragment();d&&c.setRawFragment(b.getRawFragment());return c}function k(a,b,c,d,e,f,k){this.I=a;this.F=b;this.G=c;this.K=d;this.B=e;this.w=f;this.H=k;this.j=null}function l(a){return"string"==typeof a&&0<a.length?
a:null}var p=/(\/|^)(?:[^./][^/]*|\.{2,}(?:[^./][^/]*)|\.{3,}[^/]*)\/\.\.(?:\/|$)/,r=new RegExp(p),q=/^(?:\.\.\/)*(?:\.\.$)?/;k.prototype.toString=function(){var a=[];null!==this.I&&a.push(this.I,":");null!==this.G&&(a.push("//"),null!==this.F&&a.push(this.F,"@"),a.push(this.G),null!==this.K&&a.push(":",this.K.toString()));null!==this.B&&a.push(this.B);null!==this.w&&a.push("?",this.w);null!==this.H&&a.push("#",this.H);return a.join("")};k.prototype.clone=function(){return new k(this.I,this.F,this.G,
this.K,this.B,this.w,this.H)};k.prototype.getScheme=function(){return this.I&&decodeURIComponent(this.I).toLowerCase()};k.prototype.getRawScheme=function(){return this.I};k.prototype.setScheme=function(a){this.I=d(a,w);return this};k.prototype.setRawScheme=function(a){this.I=a?a:null;return this};k.prototype.hasScheme=function(){return null!==this.I};k.prototype.getCredentials=function(){return this.F&&decodeURIComponent(this.F)};k.prototype.getRawCredentials=function(){return this.F};k.prototype.setCredentials=
function(a){this.F=d(a,w);return this};k.prototype.setRawCredentials=function(a){this.F=a?a:null;return this};k.prototype.hasCredentials=function(){return null!==this.F};k.prototype.getDomain=function(){return this.G&&decodeURIComponent(this.G)};k.prototype.getRawDomain=function(){return this.G};k.prototype.setDomain=function(a){return this.setRawDomain(a&&encodeURIComponent(a))};k.prototype.setRawDomain=function(a){this.G=a?a:null;return this.setRawPath(this.B)};k.prototype.hasDomain=function(){return null!==
this.G};k.prototype.getPort=function(){return this.K&&decodeURIComponent(this.K)};k.prototype.setPort=function(a){if(a){a=Number(a);if(a!==(a&65535))throw Error("Bad port number "+a);this.K=""+a}else this.K=null;return this};k.prototype.hasPort=function(){return null!==this.K};k.prototype.getPath=function(){return this.B&&decodeURIComponent(this.B)};k.prototype.getRawPath=function(){return this.B};k.prototype.setPath=function(a){return this.setRawPath(d(a,A))};k.prototype.setRawPath=function(a){a?
(a=String(a),this.B=!this.G||/^\//.test(a)?a:"/"+a):this.B=null;return this};k.prototype.hasPath=function(){return null!==this.B};k.prototype.getQuery=function(){return this.w&&decodeURIComponent(this.w).replace(/\+/g," ")};k.prototype.getRawQuery=function(){return this.w};k.prototype.setQuery=function(a){this.j=null;this.w=c(a);return this};k.prototype.setRawQuery=function(a){this.j=null;this.w=a?a:null;return this};k.prototype.hasQuery=function(){return null!==this.w};k.prototype.setAllParameters=
function(a){if("object"===typeof a&&!(a instanceof Array)&&(a instanceof Object||"[object Array]"!==Object.prototype.toString.call(a))){var b=[],c=-1,d;for(d in a){var e=a[d];"string"===typeof e&&(b[++c]=d,b[++c]=e)}a=b}this.j=null;for(var f=[],k="",g=0;g<a.length;)d=a[g++],e=a[g++],f.push(k,encodeURIComponent(d.toString())),k="&",e&&f.push("=",encodeURIComponent(e.toString()));this.w=f.join("");return this};k.prototype.N=function(){if(!this.j){var a=this.w;if(a){for(var b=a.split(/[&\?]/),a=[],c=
-1,d=0;d<b.length;++d){var e=b[d].match(/^([^=]*)(?:=(.*))?$/);a[++c]=decodeURIComponent(e[1]).replace(/\+/g," ");a[++c]=decodeURIComponent(e[2]||"").replace(/\+/g," ")}this.j=a}else this.j=[]}};k.prototype.setParameterValues=function(a,b){"string"===typeof b&&(b=[b]);this.N();for(var c=0,d=this.j,e=[],f=0;f<d.length;f+=2)a===d[f]?c<b.length&&e.push(a,b[c++]):e.push(d[f],d[f+1]);for(;c<b.length;)e.push(a,b[c++]);this.setAllParameters(e);return this};k.prototype.removeParameter=function(a){return this.setParameterValues(a,
[])};k.prototype.getAllParameters=function(){this.N();return this.j.slice(0,this.j.length)};k.prototype.getParameterValues=function(a){this.N();for(var b=[],c=0;c<this.j.length;c+=2)a===this.j[c]&&b.push(this.j[c+1]);return b};k.prototype.getParameterMap=function(){this.N();for(var a={},b=0;b<this.j.length;b+=2){var c=this.j[b++],d=this.j[b++];c in a?a[c].push(d):a[c]=[d]}return a};k.prototype.getParameterValue=function(a){this.N();for(var b=0;b<this.j.length;b+=2)if(a===this.j[b])return this.j[b+
1];return null};k.prototype.getFragment=function(){return this.H&&decodeURIComponent(this.H)};k.prototype.getRawFragment=function(){return this.H};k.prototype.setFragment=function(a){this.H=a?encodeURIComponent(a):null;return this};k.prototype.setRawFragment=function(a){this.H=a?a:null;return this};k.prototype.hasFragment=function(){return null!==this.H};var u=/^(?:([^:/?#]+):)?(?:\/\/(?:([^/?#]*)@)?([^/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,w=/[#\/\?@]/g,A=/[\#\?]/g;k.parse=a;
k.create=b;k.resolve=h;k.collapse_dots=g;k.utils={mimeTypeOf:function(b){var c=a(b);return/\.html$/.test(c.getPath())?"text/html":"application/javascript"},resolve:function(b,c){return b?h(a(b),a(c)).toString():""+c}};return k}(),Z={atype:{NONE:0,URI:1,URI_FRAGMENT:11,SCRIPT:2,STYLE:3,HTML:12,ID:4,IDREF:5,IDREFS:6,GLOBAL_NAME:7,LOCAL_NAME:8,CLASSES:9,FRAME_TARGET:10,MEDIA_QUERY:13}};Z.atype=Z.atype;
Z.ATTRIBS={"*::class":9,"*::dir":0,"*::draggable":0,"*::hidden":0,"*::id":4,"*::inert":0,"*::itemprop":0,"*::itemref":6,"*::itemscope":0,"*::lang":0,"*::onblur":2,"*::onchange":2,"*::onclick":2,"*::ondblclick":2,"*::onerror":2,"*::onfocus":2,"*::onkeydown":2,"*::onkeypress":2,"*::onkeyup":2,"*::onload":2,"*::onmousedown":2,"*::onmousemove":2,"*::onmouseout":2,"*::onmouseover":2,"*::onmouseup":2,"*::onreset":2,"*::onscroll":2,"*::onselect":2,"*::onsubmit":2,"*::ontouchcancel":2,"*::ontouchend":2,"*::ontouchenter":2,
"*::ontouchleave":2,"*::ontouchmove":2,"*::ontouchstart":2,"*::onunload":2,"*::spellcheck":0,"*::style":3,"*::tabindex":0,"*::title":0,"*::translate":0,"a::accesskey":0,"a::coords":0,"a::href":1,"a::hreflang":0,"a::name":7,"a::onblur":2,"a::onfocus":2,"a::shape":0,"a::target":10,"a::type":0,"area::accesskey":0,"area::alt":0,"area::coords":0,"area::href":1,"area::nohref":0,"area::onblur":2,"area::onfocus":2,"area::shape":0,"area::target":10,"audio::controls":0,"audio::loop":0,"audio::mediagroup":5,
"audio::muted":0,"audio::preload":0,"audio::src":1,"bdo::dir":0,"blockquote::cite":1,"br::clear":0,"button::accesskey":0,"button::disabled":0,"button::name":8,"button::onblur":2,"button::onfocus":2,"button::type":0,"button::value":0,"canvas::height":0,"canvas::width":0,"caption::align":0,"col::align":0,"col::char":0,"col::charoff":0,"col::span":0,"col::valign":0,"col::width":0,"colgroup::align":0,"colgroup::char":0,"colgroup::charoff":0,"colgroup::span":0,"colgroup::valign":0,"colgroup::width":0,
"command::checked":0,"command::command":5,"command::disabled":0,"command::icon":1,"command::label":0,"command::radiogroup":0,"command::type":0,"data::value":0,"del::cite":1,"del::datetime":0,"details::open":0,"dir::compact":0,"div::align":0,"dl::compact":0,"fieldset::disabled":0,"font::color":0,"font::face":0,"font::size":0,"form::accept":0,"form::action":1,"form::autocomplete":0,"form::enctype":0,"form::method":0,"form::name":7,"form::novalidate":0,"form::onreset":2,"form::onsubmit":2,"form::target":10,
"h1::align":0,"h2::align":0,"h3::align":0,"h4::align":0,"h5::align":0,"h6::align":0,"hr::align":0,"hr::noshade":0,"hr::size":0,"hr::width":0,"iframe::align":0,"iframe::frameborder":0,"iframe::height":0,"iframe::marginheight":0,"iframe::marginwidth":0,"iframe::width":0,"img::align":0,"img::alt":0,"img::border":0,"img::height":0,"img::hspace":0,"img::ismap":0,"img::name":7,"img::src":1,"img::usemap":11,"img::vspace":0,"img::width":0,"input::accept":0,"input::accesskey":0,"input::align":0,"input::alt":0,
"input::autocomplete":0,"input::checked":0,"input::disabled":0,"input::inputmode":0,"input::ismap":0,"input::list":5,"input::max":0,"input::maxlength":0,"input::min":0,"input::multiple":0,"input::name":8,"input::onblur":2,"input::onchange":2,"input::onfocus":2,"input::onselect":2,"input::pattern":0,"input::placeholder":0,"input::readonly":0,"input::required":0,"input::size":0,"input::src":1,"input::step":0,"input::type":0,"input::usemap":11,"input::value":0,"ins::cite":1,"ins::datetime":0,"label::accesskey":0,
"label::for":5,"label::onblur":2,"label::onfocus":2,"legend::accesskey":0,"legend::align":0,"li::type":0,"li::value":0,"map::name":7,"menu::compact":0,"menu::label":0,"menu::type":0,"meter::high":0,"meter::low":0,"meter::max":0,"meter::min":0,"meter::optimum":0,"meter::value":0,"ol::compact":0,"ol::reversed":0,"ol::start":0,"ol::type":0,"optgroup::disabled":0,"optgroup::label":0,"option::disabled":0,"option::label":0,"option::selected":0,"option::value":0,"output::for":6,"output::name":8,"p::align":0,
"pre::width":0,"progress::max":0,"progress::min":0,"progress::value":0,"q::cite":1,"select::autocomplete":0,"select::disabled":0,"select::multiple":0,"select::name":8,"select::onblur":2,"select::onchange":2,"select::onfocus":2,"select::required":0,"select::size":0,"source::type":0,"table::align":0,"table::bgcolor":0,"table::border":0,"table::cellpadding":0,"table::cellspacing":0,"table::frame":0,"table::rules":0,"table::summary":0,"table::width":0,"tbody::align":0,"tbody::char":0,"tbody::charoff":0,
"tbody::valign":0,"td::abbr":0,"td::align":0,"td::axis":0,"td::bgcolor":0,"td::char":0,"td::charoff":0,"td::colspan":0,"td::headers":6,"td::height":0,"td::nowrap":0,"td::rowspan":0,"td::scope":0,"td::valign":0,"td::width":0,"template::type":0,"textarea::accesskey":0,"textarea::autocomplete":0,"textarea::cols":0,"textarea::disabled":0,"textarea::inputmode":0,"textarea::name":8,"textarea::onblur":2,"textarea::onchange":2,"textarea::onfocus":2,"textarea::onselect":2,"textarea::placeholder":0,"textarea::readonly":0,
"textarea::required":0,"textarea::rows":0,"textarea::wrap":0,"tfoot::align":0,"tfoot::char":0,"tfoot::charoff":0,"tfoot::valign":0,"th::abbr":0,"th::align":0,"th::axis":0,"th::bgcolor":0,"th::char":0,"th::charoff":0,"th::colspan":0,"th::headers":6,"th::height":0,"th::nowrap":0,"th::rowspan":0,"th::scope":0,"th::valign":0,"th::width":0,"thead::align":0,"thead::char":0,"thead::charoff":0,"thead::valign":0,"tr::align":0,"tr::bgcolor":0,"tr::char":0,"tr::charoff":0,"tr::valign":0,"track::default":0,"track::kind":0,
"track::label":0,"track::srclang":0,"ul::compact":0,"ul::type":0,"video::controls":0,"video::height":0,"video::loop":0,"video::mediagroup":5,"video::muted":0,"video::poster":1,"video::preload":0,"video::src":1,"video::width":0};Z.ATTRIBS=Z.ATTRIBS;Z.eflags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,SCRIPT:64,STYLE:128,VIRTUALIZED:256};Z.eflags=Z.eflags;
Z.ELEMENTS={a:0,abbr:0,acronym:0,address:0,applet:272,area:2,article:0,aside:0,audio:0,b:0,base:274,basefont:274,bdi:0,bdo:0,big:0,blockquote:0,body:305,br:2,button:0,canvas:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,command:2,data:0,datalist:0,dd:1,del:0,details:0,dfn:0,dialog:272,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,figcaption:0,figure:0,font:0,footer:0,form:0,frame:274,frameset:272,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:305,header:0,hgroup:0,hr:2,html:305,i:0,iframe:4,img:2,input:2,ins:0,
isindex:274,kbd:0,keygen:274,label:0,legend:0,li:1,link:274,map:0,mark:0,menu:0,meta:274,meter:0,nav:0,nobr:0,noembed:276,noframes:276,noscript:276,object:272,ol:0,optgroup:0,option:1,output:0,p:1,param:274,pre:0,progress:0,q:0,s:0,samp:0,script:84,section:0,select:0,small:0,source:2,span:0,strike:0,strong:0,style:148,sub:0,summary:0,sup:0,table:0,tbody:1,td:1,template:4,textarea:8,tfoot:1,th:1,thead:1,time:0,title:280,tr:1,track:2,tt:0,u:0,ul:0,"var":0,video:0,wbr:2};Z.ELEMENTS=Z.ELEMENTS;
Z.ELEMENT_DOM_INTERFACES={a:"HTMLAnchorElement",abbr:"HTMLElement",acronym:"HTMLElement",address:"HTMLElement",applet:"HTMLAppletElement",area:"HTMLAreaElement",article:"HTMLElement",aside:"HTMLElement",audio:"HTMLAudioElement",b:"HTMLElement",base:"HTMLBaseElement",basefont:"HTMLBaseFontElement",bdi:"HTMLElement",bdo:"HTMLElement",big:"HTMLElement",blockquote:"HTMLQuoteElement",body:"HTMLBodyElement",br:"HTMLBRElement",button:"HTMLButtonElement",canvas:"HTMLCanvasElement",caption:"HTMLTableCaptionElement",
center:"HTMLElement",cite:"HTMLElement",code:"HTMLElement",col:"HTMLTableColElement",colgroup:"HTMLTableColElement",command:"HTMLCommandElement",data:"HTMLElement",datalist:"HTMLDataListElement",dd:"HTMLElement",del:"HTMLModElement",details:"HTMLDetailsElement",dfn:"HTMLElement",dialog:"HTMLDialogElement",dir:"HTMLDirectoryElement",div:"HTMLDivElement",dl:"HTMLDListElement",dt:"HTMLElement",em:"HTMLElement",fieldset:"HTMLFieldSetElement",figcaption:"HTMLElement",figure:"HTMLElement",font:"HTMLFontElement",
footer:"HTMLElement",form:"HTMLFormElement",frame:"HTMLFrameElement",frameset:"HTMLFrameSetElement",h1:"HTMLHeadingElement",h2:"HTMLHeadingElement",h3:"HTMLHeadingElement",h4:"HTMLHeadingElement",h5:"HTMLHeadingElement",h6:"HTMLHeadingElement",head:"HTMLHeadElement",header:"HTMLElement",hgroup:"HTMLElement",hr:"HTMLHRElement",html:"HTMLHtmlElement",i:"HTMLElement",iframe:"HTMLIFrameElement",img:"HTMLImageElement",input:"HTMLInputElement",ins:"HTMLModElement",isindex:"HTMLUnknownElement",kbd:"HTMLElement",
keygen:"HTMLKeygenElement",label:"HTMLLabelElement",legend:"HTMLLegendElement",li:"HTMLLIElement",link:"HTMLLinkElement",map:"HTMLMapElement",mark:"HTMLElement",menu:"HTMLMenuElement",meta:"HTMLMetaElement",meter:"HTMLMeterElement",nav:"HTMLElement",nobr:"HTMLElement",noembed:"HTMLElement",noframes:"HTMLElement",noscript:"HTMLElement",object:"HTMLObjectElement",ol:"HTMLOListElement",optgroup:"HTMLOptGroupElement",option:"HTMLOptionElement",output:"HTMLOutputElement",p:"HTMLParagraphElement",param:"HTMLParamElement",
pre:"HTMLPreElement",progress:"HTMLProgressElement",q:"HTMLQuoteElement",s:"HTMLElement",samp:"HTMLElement",script:"HTMLScriptElement",section:"HTMLElement",select:"HTMLSelectElement",small:"HTMLElement",source:"HTMLSourceElement",span:"HTMLSpanElement",strike:"HTMLElement",strong:"HTMLElement",style:"HTMLStyleElement",sub:"HTMLElement",summary:"HTMLElement",sup:"HTMLElement",table:"HTMLTableElement",tbody:"HTMLTableSectionElement",td:"HTMLTableDataCellElement",template:"HTMLTemplateElement",textarea:"HTMLTextAreaElement",
tfoot:"HTMLTableSectionElement",th:"HTMLTableHeaderCellElement",thead:"HTMLTableSectionElement",time:"HTMLTimeElement",title:"HTMLTitleElement",tr:"HTMLTableRowElement",track:"HTMLTrackElement",tt:"HTMLElement",u:"HTMLElement",ul:"HTMLUListElement","var":"HTMLElement",video:"HTMLVideoElement",wbr:"HTMLElement"};Z.ELEMENT_DOM_INTERFACES=Z.ELEMENT_DOM_INTERFACES;Z.ueffects={NOT_LOADED:0,SAME_DOCUMENT:1,NEW_DOCUMENT:2};Z.ueffects=Z.ueffects;
Z.URIEFFECTS={"a::href":2,"area::href":2,"audio::src":1,"blockquote::cite":0,"command::icon":1,"del::cite":0,"form::action":2,"img::src":1,"input::src":1,"ins::cite":0,"q::cite":0,"video::poster":1,"video::src":1};Z.URIEFFECTS=Z.URIEFFECTS;Z.ltypes={UNSANDBOXED:2,SANDBOXED:1,DATA:0};Z.ltypes=Z.ltypes;
Z.LOADERTYPES={"a::href":2,"area::href":2,"audio::src":2,"blockquote::cite":2,"command::icon":1,"del::cite":2,"form::action":2,"img::src":1,"input::src":1,"ins::cite":2,"q::cite":2,"video::poster":1,"video::src":2};Z.LOADERTYPES=Z.LOADERTYPES;
(function(a){function b(a){if(t.hasOwnProperty(a))return t[a];var b=a.match(ma);return b?String.fromCharCode(parseInt(b[1],10)):(b=a.match(na))?String.fromCharCode(parseInt(b[1],16)):ia&&Ba.test(a)?(ia.innerHTML="&"+a+";",b=ia.textContent,t[a]=b):"&"+a+";"}function c(a,c){return b(c)}function d(a){return a.replace(W,"")}function e(a){return a.replace(Ca,c)}function f(a){return(""+a).replace(Da,"&amp;").replace(aa,"&lt;").replace(pa,"&gt;").replace(Fa,"&#34;")}function g(a){return a.replace(Ea,"&amp;$1").replace(aa,
"&lt;").replace(pa,"&gt;")}function h(a){var b={cdata:a.cdata||a.cdata,comment:a.comment||a.comment,endDoc:a.endDoc||a.endDoc,endTag:a.endTag||a.endTag,pcdata:a.pcdata||a.pcdata,rcdata:a.rcdata||a.rcdata,startDoc:a.startDoc||a.startDoc,startTag:a.startTag||a.startTag};return function(a,c){var d=b,e=p(a);l(d,e,0,{noMoreGT:!1,noMoreEndComments:!1},c)}}function k(a,b,c,d,e){return function(){l(a,b,c,d,e)}}function l(b,c,d,e,f){try{b.startDoc&&0==d&&b.startDoc(f);for(var m,g,n,h=d,l=c.length;h<l;){var p=
c[h++],X=c[h];switch(p){case "&":oa.test(X)?(b.pcdata&&b.pcdata("&"+X,f,O,k(b,c,h,e,f)),h++):b.pcdata&&b.pcdata("&amp;",f,O,k(b,c,h,e,f));break;case "</":(m=/^([-\w:]+)[^\'\"]*/.exec(X))?m[0].length===X.length&&">"===c[h+1]?(h+=2,n=m[1].toLowerCase(),b.endTag&&b.endTag(n,f,O,k(b,c,h,e,f))):h=r(c,h,b,f,O,e):b.pcdata&&b.pcdata("&lt;/",f,O,k(b,c,h,e,f));break;case "<":if(m=/^([-\w:]+)\s*\/?/.exec(X))if(m[0].length===X.length&&">"===c[h+1]){h+=2;n=m[1].toLowerCase();b.startTag&&b.startTag(n,[],f,O,k(b,
c,h,e,f));var Za=a.ELEMENTS[n];Za&Eb&&(h=u(c,{name:n,next:h,eflags:Za},b,f,O,e))}else h=q(c,h,b,f,O,e);else b.pcdata&&b.pcdata("&lt;",f,O,k(b,c,h,e,f));break;case "\x3c!--":if(!e.noMoreEndComments){for(g=h+1;g<l&&(">"!==c[g]||!/--$/.test(c[g-1]));g++);if(g<l){if(b.comment){var $a=c.slice(h,g).join("");b.comment($a.substr(0,$a.length-2),f,O,k(b,c,g+1,e,f))}h=g+1}else e.noMoreEndComments=!0}e.noMoreEndComments&&b.pcdata&&b.pcdata("&lt;!--",f,O,k(b,c,h,e,f));break;case "<!":if(/^\w/.test(X)){if(!e.noMoreGT){for(g=
h+1;g<l&&">"!==c[g];g++);g<l?h=g+1:e.noMoreGT=!0}e.noMoreGT&&b.pcdata&&b.pcdata("&lt;!",f,O,k(b,c,h,e,f))}else b.pcdata&&b.pcdata("&lt;!",f,O,k(b,c,h,e,f));break;case "<?":if(!e.noMoreGT){for(g=h+1;g<l&&">"!==c[g];g++);g<l?h=g+1:e.noMoreGT=!0}e.noMoreGT&&b.pcdata&&b.pcdata("&lt;?",f,O,k(b,c,h,e,f));break;case ">":b.pcdata&&b.pcdata("&gt;",f,O,k(b,c,h,e,f));break;case "":break;default:b.pcdata&&b.pcdata(p,f,O,k(b,c,h,e,f))}}b.endDoc&&b.endDoc(f)}catch(Gb){if(Gb!==O)throw Gb;}}function p(a){var b=/(<\/|<\!--|<[!?]|[&<>])/g;
a+="";if(ab)return a.split(b);for(var c=[],d=0,e;null!==(e=b.exec(a));)c.push(a.substring(d,e.index)),c.push(e[0]),d=e.index+e[0].length;c.push(a.substring(d));return c}function r(a,b,c,d,e,f){var g=w(a,b);if(!g)return a.length;c.endTag&&c.endTag(g.name,d,e,k(c,a,b,f,d));return g.next}function q(a,b,c,d,e,f){b=w(a,b);if(!b)return a.length;c.startTag&&c.startTag(b.name,b.attrs,d,e,k(c,a,b.next,f,d));return b.eflags&Eb?u(a,b,c,d,e,f):b.next}function u(b,c,d,e,f,h){var m=b.length;Aa.hasOwnProperty(c.name)||
(Aa[c.name]=new RegExp("^"+c.name+"(?:[\\s\\/]|$)","i"));for(var l=Aa[c.name],n=c.next,p=c.next+1;p<m&&("</"!==b[p-1]||!l.test(b[p]));p++);p<m&&--p;var q=b.slice(n,p).join("");if(c.eflags&a.eflags.CDATA)d.cdata&&d.cdata(q,e,f,k(d,b,p,h,e));else if(c.eflags&a.eflags.RCDATA)d.rcdata&&d.rcdata(g(q),e,f,k(d,b,p,h,e));else throw Error("bug");return p}function w(b,c){var d=/^([-\w:]+)/.exec(b[c]),e={};e.name=d[1].toLowerCase();e.eflags=a.ELEMENTS[e.name];var f=b[c].substr(d[0].length);c+=1;for(var g=b.length;c<
g&&">"!==b[c];c++)f+=b[c];if(!(g<=c)){for(var k=[];""!==f;)if(d=qa.exec(f))if(d[4]&&!d[5]||d[6]&&!d[7]){for(var h=d[4]||d[6],m=!1,l=[f,b[c++]];c<g;c++){if(m){if(">"===b[c])break}else 0<=b[c].indexOf(h)&&(m=!0);l.push(b[c])}if(g<=c)break;f=l.join("")}else{var p=d[1].toLowerCase(),q=d[2]?A(d[3]):"";k.push(p,q);f=f.substr(d[0].length)}else f=f.replace(/^[\s\S][^a-z\s]*/,"");e.attrs=k;e.next=c+1;return e}}function A(a){var b=a.charCodeAt(0);if(34===b||39===b)a=a.substr(1,a.length-2);return e(d(a))}function y(b){function c(a,
b){e||b.push(a)}var d,e;return h({startDoc:function(){d=[];e=!1},startTag:function(c,g,k){if(!e&&a.ELEMENTS.hasOwnProperty(c)){var h=a.ELEMENTS[c];if(!(h&a.eflags.FOLDABLE)){var m=b(c,g);if(m){if("object"!==typeof m)throw Error("tagPolicy did not return object (old API?)");if("attribs"in m)g=m.attribs;else throw Error("tagPolicy gave no attribs");var l,n;"tagName"in m?(n=m.tagName,l=a.ELEMENTS[n]):(n=c,l=h);if(h&a.eflags.OPTIONAL_ENDTAG){var p=d[d.length-1];!p||p.orig!==c||p.rep===n&&c===n||k.push("</",
p.rep,">")}h&a.eflags.EMPTY||d.push({orig:c,rep:n});k.push("<",n);for(var q=0,r=g.length;q<r;q+=2){var u=g[q],t=g[q+1];null!==t&&void 0!==t&&k.push(" ",u,'="',f(t),'"')}k.push(">");h&a.eflags.EMPTY&&!(l&a.eflags.EMPTY)&&k.push("</",n,">")}else e=!(h&a.eflags.EMPTY)}}},endTag:function(b,c){if(e)e=!1;else if(a.ELEMENTS.hasOwnProperty(b)){var f=a.ELEMENTS[b];if(!(f&(a.eflags.EMPTY|a.eflags.FOLDABLE))){if(f&a.eflags.OPTIONAL_ENDTAG)for(f=d.length;0<=--f;){var g=d[f].orig;if(g===b)break;if(!(a.ELEMENTS[g]&
a.eflags.OPTIONAL_ENDTAG))return}else for(f=d.length;0<=--f&&d[f].orig!==b;);if(!(0>f)){for(var k=d.length;--k>f;){var h=d[k].rep;a.ELEMENTS[h]&a.eflags.OPTIONAL_ENDTAG||c.push("</",h,">")}f<d.length&&(b=d[f].rep);d.length=f;c.push("</",b,">")}}}},pcdata:c,rcdata:c,cdata:c,endDoc:function(a){for(;d.length;d.length--)a.push("</",d[d.length-1].rep,">")}})}function F(a,b,c,d,e){if(!e)return null;try{var f=Ac.parse(""+a);if(f&&(!f.hasScheme()||Fb.test(f.getScheme()))){var g=e(f,b,c,d);return g?g.toString():
null}}catch(Uc){}return null}function z(a,b,c,d,e){c||a(b+" removed",{change:"removed",tagName:b});if(d!==e){var f="changed";d&&!e?f="removed":!d&&e&&(f="added");a(b+"."+c+" "+f,{change:f,tagName:b,attribName:c,oldValue:d,newValue:e})}}function C(a,b,c){var d;d=b+"::"+c;if(a.hasOwnProperty(d))return a[d];d="*::"+c;if(a.hasOwnProperty(d))return a[d]}function D(b,c){return C(a.ATTRIBS,b,c)}function L(b,c){return C(a.LOADERTYPES,b,c)}function G(b,c){return C(a.URIEFFECTS,b,c)}function K(b,c,d,e,f){for(var g=
0;g<c.length;g+=2){var k=c[g],h=c[g+1],l=h,p=null,m;if((m=b+"::"+k,a.ATTRIBS.hasOwnProperty(m))||(m="*::"+k,a.ATTRIBS.hasOwnProperty(m)))p=a.ATTRIBS[m];if(null!==p)switch(p){case a.atype.NONE:break;case a.atype.SCRIPT:h=null;f&&z(f,b,k,l,h);break;case a.atype.STYLE:if("undefined"===typeof Q){h=null;f&&z(f,b,k,l,h);break}var q=[];Q(h,{declaration:function(b,c){var e=b.toLowerCase();B(e,c,d?function(b){return F(b,a.ueffects.SAME_DOCUMENT,a.ltypes.SANDBOXED,{TYPE:"CSS",CSS_PROP:e},d)}:null);c.length&&
q.push(e+": "+c.join(" "))}});h=0<q.length?q.join(" ; "):null;f&&z(f,b,k,l,h);break;case a.atype.ID:case a.atype.IDREF:case a.atype.IDREFS:case a.atype.GLOBAL_NAME:case a.atype.LOCAL_NAME:case a.atype.CLASSES:h=e?e(h):h;f&&z(f,b,k,l,h);break;case a.atype.URI:h=F(h,G(b,k),L(b,k),{TYPE:"MARKUP",XML_ATTR:k,XML_TAG:b},d);f&&z(f,b,k,l,h);break;case a.atype.URI_FRAGMENT:h&&"#"===h.charAt(0)?(h=h.substring(1),h=e?e(h):h,null!==h&&void 0!==h&&(h="#"+h)):h=null;f&&z(f,b,k,l,h);break;default:h=null,f&&z(f,
b,k,l,h)}else h=null,f&&z(f,b,k,l,h);c[g+1]=h}return c}function H(b,c,d){return function(e,f){if(a.ELEMENTS[e]&a.eflags.UNSAFE)d&&z(d,e,void 0,void 0,void 0);else return{attribs:K(e,f,b,c,d)}}}function M(a,b){var c=[];y(b)(a,c);return c.join("")}function P(a,b,c,d){b=H(b,c,d);return M(a,b)}var Q,B,x;"undefined"!==typeof window&&(Q=window.parseCssDeclarations,B=window.sanitizeCssProperty,x=window.cssSchema);var t={lt:"<",LT:"<",gt:">",GT:">",amp:"&",AMP:"&",quot:'"',apos:"'",nbsp:"\u00a0"},ma=/^#(\d+)$/,
na=/^#x([0-9A-Fa-f]+)$/,Ba=/^[A-Za-z][A-Za-z0-9]+$/,ia="undefined"!==typeof window&&window.document?window.document.createElement("textarea"):null,W=/\0/g,Ca=/&(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/g,oa=/^(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/,Da=/&/g,Ea=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,aa=/[<]/g,pa=/>/g,Fa=/\"/g,qa=/^\s*(\[[-.:\w]+\]|[-.:\w]+)(?:\s*(=)\s*((")[^"]*("|$)|(')[^']*('|$)|(?=[a-z][-\w]*\s*=)|[^"'\s]*))?/i,ab=3==="a,b".split(/(,)/).length,Eb=a.eflags.CDATA|a.eflags.RCDATA,O={},Aa=
{},Fb=/^(?:https?|geo|mailto|sms|tel)$/i,N={};N.escapeAttrib=N.escapeAttrib=f;N.makeHtmlSanitizer=N.makeHtmlSanitizer=y;N.makeSaxParser=N.makeSaxParser=h;N.makeTagPolicy=N.makeTagPolicy=H;N.normalizeRCData=N.normalizeRCData=g;N.sanitize=N.sanitize=P;N.sanitizeAttribs=N.sanitizeAttribs=K;N.sanitizeWithPolicy=N.sanitizeWithPolicy=M;N.unescapeEntities=N.unescapeEntities=e;return N})(Z);wa({applet:!0,audio:!0,base:!0,embed:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,script:!0,style:!0,svg:!0,video:!0});wa({br:!0,col:!0,hr:!0,img:!0,input:!0,source:!0,track:!0,wbr:!0,area:!0,base:!0,command:!0,embed:!0,keygen:!0,link:!0,meta:!0,param:!0});wa({a:["rel"],div:["template"],form:["action-xhr","custom-validation-reporting","target"],template:["type"]});wa({input:{type:/(?:image|file|button)/i}});var Bc="form formaction formmethod formtarget formnovalidate formenctype".split(" ");
wa({input:Bc,textarea:Bc,select:Bc});function Cc(a,b,c){var d=self.location;Ua(c);var e=Ra(d),f=S(Sa(d));if("href"==b&&!R(c,"#"))return Ta(c,f);if("src"==b)return"amp-img"==a?Dc(c,f,e):Ta(c,f);if("srcset"==b){var g;try{g=ac(c)}catch(h){return I().error("sanitizer","Failed to parse srcset: ",h),c}return g.stringify(function(a){return Dc(a,f,e)})}return c}
function Dc(a,b,c){a=S(Ta(a,b));return"data:"==a.protocol||Ra(a)||!c?a.href:Ha+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var Ec=/^(i?-)?amp(html)?-/,Fc=J({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state"],"AMP-SELECTOR":["selected"]});
function Gc(a,b){var c=this;this.ampdoc=a;this.o=a.win;this.Z=b||a.win;this.L=[];this.pa=this.ta.bind(this);this.M=J();this.ga=T(a,"history");this.ja=[];this.$=2E3;this.la=T(a,"resources");this.R=J();this.ya=U(this.o,"timer");this.za=new ic;this.D=T(this.ampdoc,"viewer");this.D.onMessageRespond("premutate",this.ua.bind(this));var d=b?nb(b.document).then(function(){return b.document.body}):a.whenBodyAvailable();this.U=this.D.whenFirstVisible().then(function(){return d}).then(function(d){var e=b?b.document.head:
a.getHeadNode();return c.Y(d,e&&ob(e))});this.W=null;AMP.printState=this.va.bind(this)}v=Gc.prototype;v.adoptEmbedWindow=function(a){bb(a,new Gc(this.ampdoc,a))};v.setState=function(a,b,c){var d=this;try{ya(this.R,a)}catch(e){I().error("amp-bind","Failed to merge result from AMP.setState().",e)}return b?Promise.resolve():this.W=this.U.then(function(){return Hc(d)}).then(function(a){return Ic(d,a,c)})};v.setStateWithExpression=function(a,b){var c=this;return this.W=Jc(this,a,b).then(function(a){return c.setState(a)})};
v.pushStateWithExpression=function(a,b){var c=this;return Jc(this,a,b).then(function(a){function b(){return c.setState(d)}var d=J();Object.keys(a).forEach(function(a){var b;a:{var e=c.R[a];if(void 0!==e)try{b=JSON.parse(JSON.stringify(e));break a}catch(l){ua().error("amp-bind","Failed to copy JSON ("+e+") with error: "+l)}b=null}d[a]=b});c.ga.push(b);return c.setState(a)})};
v.scanAndApply=function(a,b,c){c=void 0===c?2E3:c;var d=this,e=Kc(this,b).then(function(){return Lc(d,a)}).then(function(b){if(0<b)return Hc(d).then(function(b){return Mc(d,b,a)})});return this.ya.timeoutPromise(c,e,"Timed out waiting for amp-bind to process rendered template.")};
v.Y=function(a,b){var c=this,d=[a];b&&d.push(b);d=Promise.all([Nc(this),Lc(this,d)]).then(function(){a.addEventListener("amp:dom-update",c.pa)});E().development&&(d=d.then(function(){return Hc(c).then(function(a){return c.Aa(a)})}));return d};v.numberOfBindings=function(){return this.L.reduce(function(a,b){return a+b.boundProperties.length},0)};v.Ja=function(a){this.$=a};v.Ga=function(){return this.ga};
v.ua=function(a){var b=this,c=[];return this.U.then(function(){Object.keys(a.state).forEach(function(d){b.ja.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&I().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};v.makeStateKeyOverridable=function(a){this.ja.push(a)};
function Nc(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];pb(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Oc(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){Pc(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function Lc(a,b){var c=b.map(function(b){var c=a.$-a.numberOfBindings();return Qc(a,b,c).then(function(b){var c=b.boundElements,d=b.bindings,e=b.expressionToElements,f=b.limitExceeded;a.L=a.L.concat(c);Object.assign(a.M,e);f&&I().error("amp-bind","Maximum number of bindings reached "+("("+a.$+"). Additional elements with ")+"bindings will be ignored.");return d})});return Promise.all(c).then(function(b){var c=Array.prototype.concat.apply([],b);return 0==c.length?c.length:Oc(a,"bind.addBindings",[c]).then(function(b){Object.keys(b).forEach(function(c){var d=
a.M[c];0<d.length&&Pc(b[c],'amp-bind: Expression compile error in "'+c+'".',d[0])});return c.length})})}
function Kc(a,b){E().development&&a.numberOfBindings();Sb(a.L,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!1;return!0});E().development&&a.numberOfBindings();var c=[],d;for(d in a.M){var e=a.M[d];Sb(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!1;return!0});0==e.length&&(c.push(d),delete a.M[d])}return 0<c.length?Oc(a,"bind.removeBindingsWithExpressionStrings",[c]):Promise.resolve()}
function Qc(a,b,c){function d(){var b=h.currentNode;if(!b)return!0;var d=b.tagName,r=Rc(a,b);f.length+r.length>c&&(r=r.slice(0,c-f.length),k=!0);0<r.length&&e.push({element:b,boundProperties:r});r.forEach(function(a){var c=a,e=c.expressionString;f.push({tagName:d,property:c.property,expressionString:e});g[e]||(g[e]=[]);g[e].push(b)});return!h.nextNode()||k}var e=[],f=[],g=J(),h=b.ownerDocument.createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),k=!1;return new Promise(function(b){function c(h){var l=
!1;if(h&&!h.didTimeout)for(;1<h.timeRemaining()&&!l;)l=d();else{var p=250;for(h=0;h<p&&!l;h++)l=d()}l?b({boundElements:e,bindings:f,expressionToElements:g,limitExceeded:k}):nc(a.ampdoc,c)}nc(a.ampdoc,c)})}
function Rc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){var g;a:{var h=a,k=d[e];g=b;var l=g.tagName,p=k.name;if(2<p.length&&"["===p[0]&&"]"===p[p.length-1]){p=p.substr(1,p.length-2);if(h.za.canBind(l,p)){g={property:p,expressionString:k.value};break a}h=I().createError("amp-bind: Binding to ["+p+"] on <"+l+"> is not allowed.");V(h,g)}g=null}g&&c.push(g)}return c}
function Jc(a,b,c){return a.U.then(function(){Object.assign(c,a.R);return Oc(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw Pc(a,"amp-bind: Expression eval failed.");return b})}
function Hc(a){var b=Oc(a,"bind.evaluateBindings",[a.R]);return b.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.M[b];if(0<c.length){var d=e[b],f=I().createError('amp-bind: Expression evaluation error in "'+b+'". '+d.message);f.stack=d.stack;V(f,c[0])}});return c})}
v.Aa=function(a){this.L.forEach(function(b){var c=b.element;b.boundProperties.forEach(function(b){var d=a[b.expressionString];if(void 0!==d){var f=b.property;b=b.expressionString;var g=c.tagName,h=Fc[g];if(!h||!h.includes(f)){switch(f){case "text":h=c.textContent;d=String(d);h=h.trim()===d.trim();break;case "class":for(var h=[],k=0;k<c.classList.length;k++){var l=c.classList[k];Ec.test(l)||h.push(l)}k=[];Array.isArray(d)?k=d:"string"===typeof d?(l=d.trim(),0<l.length&&(k=l.split(" "))):(l=I().createError('amp-bind: "'+
d+'" is not a valid result for [class].'),V(l,c));a:if(l=k,h.length!==l.length)h=!1;else{for(var k=(Array.isArray(h)?h:ja(h)).sort(),l=(Array.isArray(l)?l:ja(l)).sort(),p=0;p<h.length;p++)if(k[p]!==l[p]){h=!1;break a}h=!0}break;default:h=c.getAttribute(f),h=!0===d?""===h:!1===d?null===h:h===d}h||I().warn("amp-bind","Default value for <"+g+" ["+f+']="'+b+'"> '+("does not match first result ("+d+"). We recommend ")+"writing expressions with matching default values, but this can be safely ignored if intentional.")}}})})};
function Sc(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||Wa(f,d,5)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}function Ic(a,b,c){var d=a.L.map(function(d){return c&&"AMP-STATE"==d.element.tagName?Promise.resolve():Tc(a,b,d)});return Promise.all(d)}function Mc(a,b,c){var d=[];a.L.forEach(function(e){c.forEach(function(c){c.contains(e.element)&&d.push(Tc(a,b,e))})});return Promise.all(d)}
function Tc(a,b,c){var d=c.element,e=Sc(c.boundProperties,b);return 0===e.length?Promise.resolve():a.la.mutateElement(d,function(){var b={},c,h;e.forEach(function(e){var f=e,k=f.boundProperty,f=f.newValue,g;a:{g=k.property;var l=d.tagName;switch(g){case "text":d.textContent=String(f);"TITLE"===l&&d.parentNode===a.Z.document.head&&(a.Z.document.title=String(f));"TEXTAREA"==l&&(d.value=String(f));break;case "class":g=[];for(var w=0;w<d.classList.length;w++)l=d.classList[w],Ec.test(l)&&g.push(l);Array.isArray(f)||
"string"===typeof f?d.setAttribute("class",g.concat(f).join(" ")):null===f?d.setAttribute("class",g.join(" ")):(g=I().createError('amp-bind: "'+f+'" is not a valid result for [class].'),V(g,d));break;default:var l="INPUT"==l&&g in d,A=d.getAttribute(g),y=!1;if("boolean"===typeof f)l&&d[g]!==f&&(d[g]=f,y=!0),f&&""!==A?(d.setAttribute(g,""),y=!0):f||null===A||(d.removeAttribute(g),y=!0);else if(f!==A){A=String(f);try{var F=d.tagName.toLowerCase(),z=g.toLowerCase(),C=F.toLowerCase(),D=z.toLowerCase(),
L="src"==D||"href"==D||"srcset"==D?Cc(C,D,A):A;if(Ra(self.location)&&"a"===F&&"href"===z){var G=d.getAttribute(z),K="#"===L[0],H=G&&"#"===G[0];K&&!H?(d.__AMP_ORIGINAL_TARGET_VALUE_||(d.__AMP_ORIGINAL_TARGET_VALUE_=d.getAttribute("target")),d.removeAttribute("target")):H&&!K&&d.setAttribute("target",d.__AMP_ORIGINAL_TARGET_VALUE_||"_top")}d.setAttribute(z,L);w=L}catch(P){F=I().createError('amp-bind: "'+A+'" is not a '+("valid result for ["+g+"]"),P),V(F,d)}w&&(l&&(d[g]=w),y=!0)}if(y){g={name:g,value:f};
break a}}g=null}var M=g;M&&(b[M.name]=M.value,k=k.property,"width"==k?c="number"===typeof f&&isFinite(f)?Number(f):c:"height"==k&&(h="number"===typeof f&&isFinite(f)?Number(f):h))});void 0===c&&void 0===h||a.la.changeSize(d,h,c);if("function"===typeof d.mutatedAttributesCallback)try{d.mutatedAttributesCallback(b)}catch(l){var k=I().createError("amp-bind: Applying expression "+("results ("+JSON.stringify(b)+") failed with error"),l);V(k,d)}})}
v.ta=function(a){var b=this,c=a.target;(a=c.parentNode)&&"AMP-LIST"==a.tagName?ua().info("amp-bind","Skipping DOM_UPDATE rescan of:",c):Kc(this,[c]).then(function(){return Lc(b,[c])}).then(function(){})};function Oc(a,b,c){var d=a.o;a=a.Z;if(d.Worker){var e;e=cb(d);db(e,e,"amp-worker",yc);d=U(d,"amp-worker");b=zc(d,b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function Pc(a,b,c){b=I().createError(b+" "+a.message);b.stack=a.stack;V(b,c);return b}
v.va=function(){var a=[],b=JSON.stringify(this.R,function(b,d){if(ka(d)){if(a.includes(d))return"[Circular]";a.push(d)}return d});I().info("amp-bind",b)};v.Ha=function(){return this.U};v.Ka=function(){return this.W};(function(a){a.registerServiceForDoc("bind",Gc);a.registerElement("amp-state",Vb);a.registerElement("amp-bind-macro",Tb)})(self.AMP);
})});
//# sourceMappingURL=amp-bind-0.1.js.map

