(self.AMP=self.AMP||[]).push({n:"amp-iframe",v:"1525381599226",f:(function(AMP){var l;function aa(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c]}function p(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;self.log=self.log||{user:null,dev:null,userForEmbed:null};var t=self.log;function u(){if(!t.user)throw Error("failed to call initLogConstructor");return t.user}function v(){if(t.dev)return t.dev;throw Error("failed to call initLogConstructor");};function x(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function y(a){return a||{}};function z(a){this.Y=a;this.l=Object.create(null)}z.prototype.get=function(a){if(this.l[a])return this.l[a].access=Date.now(),this.l[a].payload};z.prototype.put=function(a,b){var d=this;this.l[a]={payload:b,access:Date.now()};var c=Object.keys(this.l);c.length>this.Y&&(v().warn("lru-cache","Trimming template cache"),c.sort(function(a,b){return d.l[b].access-d.l[a].access}),delete this.l[c[c.length-1]])};function A(a,b){var d=a.length-b.length;return 0<=d&&a.indexOf(b,d)==d};var ca=(self.AMP_CONFIG||{}).thirdPartyFrameHost||"ampproject.net";y({c:!0,v:!0,a:!0,ad:!0});var C,D;
function E(a){var b;C||(C=self.document.createElement("a"),D=self.UrlCache||(self.UrlCache=new z(100)));var d=D.get(a);if(d)return d;var c=C;c.href=a;c.protocol||(c.href=c.href);var e={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=c.origin&&
"null"!=c.origin?c.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var g=e,f=g;if(b)return f;D.put(a,f);return f}function da(a){"string"==typeof a&&(a=E(a));return"https:"==a.protocol||"localhost"==a.hostname||A(a.hostname,".localhost")};function ea(a,b){try{return JSON.parse(a)}catch(d){b&&b(d)}};function F(a,b){a=a.__AMP_TOP||a;return G(a,b)}function H(a){return a.nodeType?F((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function G(a,b){I(a,b);var d=a.services;d||(d=a.services={});var c=d;a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function I(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function fa(a,b){for(var d,c=a;c&&c!==d;c=c.parentElement)if(b(c))return c;return null}function ga(a){return a.closest?a.closest(".i-amphtml-overlay"):fa(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,".i-amphtml-overlay"):!1})};function ha(a){var b;if(a.__AMP__EXPERIMENT_TOGGLES)b=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var c=a.AMP_CONFIG[d];"number"===typeof c&&0<=c&&1>=c&&(b[d]=Math.random()<c)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],c=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var c=
c.getAttribute("content").split(","),e=0;e<c.length;e++)-1!=d.indexOf(c[e])&&(b[c[e]]=!0);Object.assign(b,ia(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){d=a.AMP_CONFIG["allow-url-opt-in"];c=a.location.originalHash||a.location.hash;a=Object.create(null);if(c)for(var g;g=ba.exec(c);)e=p(g[1],g[1]),g=g[2]?p(g[2],g[2]):"",a[e]=g;for(c=0;c<d.length;c++)e=a["e-"+d[c]],"1"==e&&(b[d[c]]=!0),"0"==e&&(b[d[c]]=!1)}}var f=b;return!!f["iframe-messaging"]}
function ia(a){a:{var b;try{b=a.document.cookie}catch(k){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var d=a[b].trim(),c=d.indexOf("="),e;if(e=-1!=c)e=d.substring(0,c).trim(),e="AMP_EXP"==p(e,void 0);if(e){a=d.substring(c+1).trim();a=p(a,a);break a}}a=null}var g=a,f=g?g.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};var J,K="Webkit webkit Moz moz ms O o".split(" ");function L(a,b){var d,c;c=a.style;J||(J=x());var e=J.zIndex;if(!e){e="zIndex";if(void 0===c.zIndex){var g;b:{for(g=0;g<K.length;g++){var f=K[g]+"ZIndex";if(void 0!==c[f]){g=f;break b}}g=""}void 0!==c[g]&&(e=g)}J.zIndex=e}c=e;c&&(a.style[c]=d?b+d:b)};var ja={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0,"AMP-LIGHTBOX-GALLERY":!0};function M(a,b,d,c){return{left:a,top:b,width:d,height:c,bottom:b+c,right:a+d,x:a,y:b}}function ka(a){for(var b=-Infinity,d=Infinity,c=-Infinity,e=Infinity,g=0;g<arguments.length;g++){var f=arguments[g];if(f&&(b=Math.max(b,f.left),d=Math.min(d,f.left+f.width),c=Math.max(c,f.top),e=Math.min(e,f.top+f.height),d<b||e<c))return null}return Infinity==d?null:M(b,c,d-b,e-c)}function N(a,b,d){return 0==b&&0==d||0==a.width&&0==a.height?a:M(a.left+b,a.top+d,a.width,a.height)};function la(a){if(!O(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(d){return v().error("MESSAGING","Failed to parse message: "+a,d),null}}function O(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function ma(a,b){for(var d=[],c=0,e=0;e<a.length;e++){var g=a[e];b(g,e,a)?(c<e&&(a[c]=g),c++):d.push(g)}c<a.length&&(a.length=c)};function P(a,b,d){var c=a.listeningFors;!c&&d&&(c=a.listeningFors=Object.create(null));a=c||null;if(!a)return a;var e=a[b];!e&&d&&(e=a[b]=[]);return e||null}function na(a,b,d){var c=E(b.src).origin,e=d?b.getAttribute("data-amp-3p-sentinel"):"amp";a=P(a,e,!0);for(var g,e=0;e<a.length;e++){var f=a[e];if(f.frame===b){g=f;break}}g||(g={frame:b,origin:c,events:Object.create(null)},a.push(g));return g.events}
function oa(a){for(var b=y({sentinel:"unlisten"}),d=a.length-1;0<=d;d--){var c=a[d];if(!c.frame.contentWindow){a.splice(d,1);var e=c.events,g;for(g in e)e[g].splice(0,Infinity).forEach(function(a){a(b)})}}}
function pa(a){if(!a.listeningFors){var b=function(b){if(b.data){var c=qa(b.data);if(c&&c.sentinel){var d;d=c.sentinel;var g=b.origin,f=b.source,k=P(a,d);if(k){for(var h,m=0;m<k.length;m++){var q=k[m],r=q.frame.contentWindow;if(r)if("amp"===d){if(q.origin===g&&r==f){h=q;break}}else{var n;if(!(n=f==r))b:{for(n=f;n&&n!=n.parent;n=n.parent)if(n==r){n=!0;break b}n=!1}if(n){h=q;break}}else setTimeout(oa,0,k)}d=h?h.events:null}else d=k;var B=d;if(B){var w=B[c.type];if(w)for(w=w.slice(),d=0;d<w.length;d++)(0,w[d])(c,
b.source,b.origin)}}}};a.addEventListener("message",b)}}function Q(a,b,d,c,e){function g(b,c,g){if(e||c==a.contentWindow)"unlisten"==b.sentinel?h():d(b,c,g)}var f=a.ownerDocument.defaultView;pa(f);c=na(f,a,c);var k=c[b]||(c[b]=[]),h;k.push(g);return h=function(){if(g){var a=k.indexOf(g);-1<a&&k.splice(a,1);d=k=g=null}}}
function ra(a,b,d,c,e){if(a.contentWindow)for(c.type=d,c.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp",a=c,e&&(a="amp-"+JSON.stringify(c)),c=0;c<b.length;c++)e=b[c],e.win.postMessage(a,e.origin)}function qa(a){"string"==typeof a&&(a="{"==a.charAt(0)?ea(a,function(a){v().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",a)})||null:O(a)?la(a):null);return a}
function R(a,b,d,c){var e=this;this.h=a;this.M=d;this.w=[];this.$=Q(this.h,b,function(a,b,d){e.w.some(function(a){return a.win==b})||e.w.push({win:b,origin:d});c(a,b,d)},this.M,this.M)}R.prototype.send=function(a,b){ma(this.w,function(a){return!!a.win.parent});ra(this.h,this.w,a,b,this.M)};R.prototype.destroy=function(){this.$();this.w.length=0};var sa=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1],ta=Date.now();function S(a,b,d){var c=this;this.K=a;this.A=null;this.P=this.S=!1;this.I=null;this.J=a.getViewport();this.T=new R(b,"send-intersections",d||!1,function(){ua(c)});this.A=new T(function(a){for(var b=0;b<a.length;b++)delete a[b].target;c.T.send("intersection",y({changes:a}))},{threshold:sa});this.A.tick(this.J.getRect());this.fire=function(){c.S&&c.P&&c.A.tick(c.J.getRect())}}
function ua(a){a.S=!0;a.A.observe(a.K.element);a.K.getVsync().measure(function(){a.P=a.K.isInViewport();a.fire()});var b=a.J.onScroll(a.fire),d=a.J.onChanged(a.fire);a.I=function(){b();d()}}S.prototype.onViewportCallback=function(a){this.P=a};S.prototype.destroy=function(){this.S=!1;this.A=null;this.I&&(this.I(),this.I=null);this.T.destroy();this.T=null};
function T(a,b){this.V=a;var d=b&&b.threshold,d=d?Array.isArray(d)?d:[d]:[0];for(a=0;a<d.length;a++){var c=d[a];"number"===typeof c&&isFinite(c)}this.Z=d.sort();this.R=null;this.X=void 0;this.j=[]}T.prototype.disconnect=function(){this.j.length=0};
T.prototype.observe=function(a){for(var b=0;b<this.j.length;b++)if(this.j[b].element===a){v().warn("INTERSECTION-OBSERVER","should observe same element once");return}var d={element:a,currentThresholdSlot:0};this.R&&(a=U(this,d,this.R,this.X))&&this.V([a]);this.j.push(d)};T.prototype.unobserve=function(a){for(var b=0;b<this.j.length;b++)if(this.j[b].element===a){this.j.splice(b,1);return}v().warn("INTERSECTION-OBSERVER","unobserve non-observed element")};
T.prototype.tick=function(a,b){b&&(a=N(a,-b.left,-b.top),b=N(b,-b.left,-b.top));this.R=a;this.X=b;for(var d=[],c=0;c<this.j.length;c++){var e=U(this,this.j[c],a,b);e&&d.push(e)}d.length&&this.V(d)};
function U(a,b,d,c){var e=b.element,g=null,f=e.getLayoutBox(),k=e.getOwner(),g=k&&k.getLayoutBox(),h=ka(f,g,d,c)||M(0,0,0,0),k=h,m=f,k=k.width*k.height/(m.width*m.height);a=a.Z;var m=0,q=a.length;if(0==k)a=0;else{for(var r=(m+q)/2|0;m<r;)k<a[r]?q=r:m=r,r=(m+q)/2|0;a=q}var n=a;if(n==b.currentThresholdSlot)return null;b.currentThresholdSlot=n;d=c?null:d;c=h;a=f;if(m=d)c=N(c,-d.left,-d.top),a=N(a,-d.left,-d.top),m=N(m,-d.left,-d.top);var B={time:"undefined"!==typeof performance&&performance.now?performance.now():
Date.now()-ta,rootBounds:m,boundingClientRect:a,intersectionRect:c,intersectionRatio:k,target:e};return B};var va="allowfullscreen allowpaymentrequest allowtransparency allow frameborder referrerpolicy scrolling".split(" "),wa=0,V=0;function W(a){a=AMP.BaseElement.call(this,a)||this;a.H=null;a.F=!1;a.N=!1;a.B=!1;a.W=!1;a.ba=null;a.L=null;a.h=null;a.G=!1;a.m=null;a.C="";a.iframeSrc=null;a.D=null;a.O=void 0;a.o=null;return a}aa(W,AMP.BaseElement);l=W.prototype;l.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
l.assertSource=function(a,b,d){var c=E(a);u().assert(da(c)||"data:"==c.protocol,"Invalid <amp-iframe> src. Must start with https://. Found %s",this.element);var e=E(b);u().assert(!(" "+d+" ").match(/\s+allow-same-origin\s+/i)||c.origin!=e.origin&&"data:"!=c.protocol,"Origin of <amp-iframe> must not be equal to container %sif allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",this.element);u().assert(!(A(c.hostname,"."+ca)||
A(c.hostname,".ampproject.org")),"amp-iframe does not allow embedding of frames from ampproject.*: %s",a);return a};
l.assertPosition=function(){var a=this.element.getLayoutBox(),b=Math.min(600,.75*this.getViewport().getSize().height);u().assert(a.top>=b,"<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): %s  Current position %s. Min: %sPositioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.",this.element,
a.top,b)};function X(a){if(a){var b=E(a);"data:"==b.protocol||b.hash&&"#"!=b.hash||(b=a.indexOf("#"),a=(-1==b?a:a.substring(0,b))+"#amp=1");return a}}
l.firstAttachedCallback=function(){this.C=this.element.getAttribute("sandbox");var a;if(!(a=X(this.element.getAttribute("src")))){a=this.element.getAttribute("srcdoc");var b=this.C;if(a){u().assert(!(" "+b+" ").match(/\s+allow-same-origin\s+/i),"allow-same-origin is not allowed with the srcdoc attribute %s.",this.element);if("undefined"!==typeof TextEncoder)b=(new TextEncoder("utf-8")).encode(a);else{a=unescape(encodeURIComponent(a));for(var b=new Uint8Array(a.length),d=0;d<a.length;d++){var c=a.charCodeAt(d);
b[d]=c}}a=btoa;d=Array(b.length);for(c=0;c<b.length;c++)d[c]=String.fromCharCode(b[c]);b=d.join("");a="data:text/html;charset=utf-8;base64,"+a(b)}else a=void 0}var e=a;this.iframeSrc=this.assertSource(e,window.location.href,this.C)};l.preconnectCallback=function(a){this.iframeSrc&&this.preconnect.url(this.iframeSrc,a)};
l.buildCallback=function(){this.H=this.getPlaceholder();this.F=!!this.H;(this.G=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0");var a;a=this.element;if("no"!=a.getAttribute("scrolling")){var b=a.ownerDocument.createElement("i-amphtml-scroll-container");a.appendChild(b);a=b}this.D=a;xa(this)};
l.onLayoutMeasure=function(){Y(this);var a;a:{var b=this.element.getLayoutBox();a=b.height;for(var b=b.width,d=0;d<Z.length;d++){var c=Z[d][0],e=Z[d][1];if(!(e>a||c>b)&&20>=a-e&&20>=b-c){a=!0;break a}}a=!1}this.N=a;a=this.element.getLayoutBox();10<a.width&&10<a.height?a=!1:(void 0===this.O&&(this.O=!!ga(this.element)),a=!this.O);this.B=a;if(a=this.N){a=this.win;b=!1;d=0;c=this.element;do ja[c.tagName]?(d++,b=!1):(e=(a.getComputedStyle(c)||x()).position,"fixed"!=e&&"sticky"!=e||(b=!0)),c=c.parentElement;
while(c&&"BODY"!=c.tagName);a=!(!b&&1>=d)}this.W=a;this.m&&this.m.fire()};function Y(a){if(a.h){var b=a.getViewport().getLayoutRect(a.h),d=a.getLayoutBox();a.L=N(b,-d.left,-d.top)}}l.getIntersectionElementLayoutBox=function(){if(!this.h)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);var a=this.getLayoutBox();this.L||Y(this);return N(this.L,a.left,a.top)};
l.layoutCallback=function(){var a=this;u().assert(!this.W,"amp-iframe is not used for displaying fixed ad. Please use amp-sticky-ad and amp-ad instead.");this.F||this.assertPosition();this.G&&u().assert(this.getOverflowElement(),"Overflow element must be defined for resizable frames: %s",this.element);if(!this.iframeSrc)return Promise.resolve();if(this.B&&(V++,1<V))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
Promise.resolve();var b=this.element.ownerDocument.createElement("iframe");this.h=b;this.applyFillContent(b);b.name="amp_iframe"+wa++;this.F&&L(b,-1);this.propagateAttributes(va,b);ya(b,this.C);b.src=this.iframeSrc;this.B||(this.m=new S(this,b));b.onload=function(){b.readyState="complete";a.U();a.B&&(a.iframeSrc=null,F(a.win,"timer").promise(5E3).then(function(){b.parentElement&&b.parentElement.removeChild(b);a.element.setAttribute("amp-removed","");a.h=null}))};Q(b,"embed-size",function(b){za(a,
b.height,b.width)});this.F&&Q(b,"embed-ready",this.U.bind(this));this.D.appendChild(b);return this.loadPromise(b).then(function(){a.D!=a.element&&F(a.win,"timer").delay(function(){a.mutateElement(function(){a.D.classList.add("amp-active")})},1E3)})};l.unlayoutOnPause=function(){return!0};l.unlayoutCallback=function(){if(this.h){var a=this.h;a.parentElement&&a.parentElement.removeChild(a);this.H&&this.togglePlaceholder(!0);this.h=null;this.m&&(this.m.destroy(),this.m=null)}return!0};
l.viewportCallback=function(a){if(this.m)this.m.onViewportCallback(a)};l.getLayoutPriority=function(){return this.N?2:this.B?1:AMP.BaseElement.prototype.getLayoutPriority.call(this)};l.mutatedAttributesCallback=function(a){var b=a.src;void 0!==b&&(this.iframeSrc=X(b),this.h&&(this.h.src=this.assertSource(this.iframeSrc,window.location.href,this.C)))};l.U=function(){var a=this;this.H&&this.getVsync().mutate(function(){a.h&&(L(a.h,0),a.togglePlaceholder(!1))})};l.firstLayoutCompleted=function(){};
function za(a,b,d){if(a.G)if(100>b)a.user().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",a.element);else{var c,e;b=parseInt(b,10);isNaN(b)||(c=Math.max(b+(a.element.offsetHeight-a.h.offsetHeight),b));d=parseInt(d,10);isNaN(d)||(e=Math.max(d+(a.element.offsetWidth-a.h.offsetWidth),d));void 0!==c||void 0!==e?a.attemptChangeSize(c,e).then(function(){void 0!==c&&a.element.setAttribute("height",
c);void 0!==e&&a.element.setAttribute("width",e)},function(){}):a.user().error("amp-iframe","Ignoring embed-size request because no width or height value is provided",a.element)}else a.user().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",a.element)}
function xa(a){if(ha(a.win)){var b=a.element.getAttribute("src");b&&(a.o=E(b).origin);a.registerAction("postMessage",function(b){a.o?a.h.contentWindow.postMessage(b.args,a.o):u().error("amp-iframe",'"postMessage" action is only allowed with "src"attribute with an origin.')},100);if(a.o){var d=10,c=0,e=function(b){if(b.source===a.h.contentWindow)if(b.origin!==a.o)u().error("amp-iframe",'"message" received from unexpected origin: '+b.origin+". Only allowed from: "+a.o);else{var f;a.getAmpDoc().getRootNode().activeElement!==
a.h?f=!1:(f=a.win.document.createElement("audio"),f.play(),f=f.paused?!1:!0);if(f){b=b.data;var g;try{g=JSON.parse(JSON.stringify(b))}catch(q){u().error("amp-iframe",'Data from "message" event must be JSON.');return}var h=a.win;b=g;f={detail:b};Object.assign(f,void 0);"function"==typeof h.CustomEvent?b=new h.CustomEvent("amp-iframe:message",f):(h=h.document.createEvent("CustomEvent"),h.initCustomEvent("amp-iframe:message",!!f.bubbles,!!f.cancelable,b),b=h);a:{f=a.getAmpDoc();if(f.nodeType&&(h=(f.ownerDocument||
f).defaultView,h=h!=(h.__AMP_TOP||h)&&I(h,"action")?G(h,"action"):null)){f=h;break a}f=H(f);f=H(f);f=f.isSingleDoc()?f.win:f;f=G(f,"action")}var m=f;m.trigger(a.element,"message",b,100)}else c++,u().error("amp-iframe",'"message" event may only be triggered from a user gesture.'),c>=d&&(u().error("amp-iframe",'Too many non-gesture-triggered "message" events; detaching event listener.'),a.win.removeEventListener("message",e))}};a.win.addEventListener("message",e)}}}l.aa=function(a){this.o=a};
function ya(a,b){var d=b||"";a.setAttribute("sandbox",d)}var Z=[[300,250],[320,50],[300,50],[320,100]];(function(a){a.registerElement("amp-iframe",W)})(self.AMP);
})});
//# sourceMappingURL=amp-iframe-0.1.js.map

